export interface FeatureModuleDefinition {
  id: string;
  module_code: string;
  name: string;
  function_group:
    | "pos"
    | "inventory"
    | "ai"
    | "crm"
    | "finance"
    | "purchases"
    | "reports"
    | "team"
    | "ecommerce"
    | "enterprise"
    | "hardware"
    | "developer";
  group_title: string;
  description: string;
  version_target: "v1" | "v2" | "v3" | "v4" | "v5";
  version_title: string;
  lifecycle_phase: "live" | "beta" | "staging" | "deactivated";
  global_active: boolean;
  plan_free: boolean;
  plan_standard: boolean;
  plan_premium: boolean;
  health: "optimal" | "high" | "moderate" | "experimental";
  latency_ms: number;
  source_file_url?: string;
  test_scenario?: {
    input_sample: string;
    expected_output: string;
    simulated_payload: Record<string, any>;
  };
}

export interface FeatureGroupMeta {
  key: FeatureModuleDefinition["function_group"];
  title: string;
  iconName: string;
  description: string;
  accent: string;
}

export const FEATURE_GROUPS: FeatureGroupMeta[] = [
  {
    key: "pos",
    title: "POS & Billing Terminal",
    iconName: "ShoppingCart",
    description: "Fast checkout, barcode scan, thermal receipts, discounts, and payment methods.",
    accent: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
  },
  {
    key: "inventory",
    title: "Inventory & Stock Control",
    iconName: "Package",
    description: "Products, categories, stock tracking, UOM units, low stock triggers & label generator.",
    accent: "text-blue-500 bg-blue-500/10 border-blue-500/20",
  },
  {
    key: "ai",
    title: "AI & Smart Automation",
    iconName: "Brain",
    description: "AI product autofill, report summaries, forecasting, vision invoice OCR & Copilot.",
    accent: "text-violet-500 bg-violet-500/10 border-violet-500/20",
  },
  {
    key: "crm",
    title: "Customer Khata & Loyalty",
    iconName: "Users",
    description: "Credit ledger (Udaar), loyalty reward points, store credit & customer directories.",
    accent: "text-amber-500 bg-amber-500/10 border-amber-500/20",
  },
  {
    key: "finance",
    title: "Finance, Profit & Expenses",
    iconName: "DollarSign",
    description: "Daily net profit, operational expense logging, tax engines (VAT/GST/ZATCA) & costing.",
    accent: "text-teal-500 bg-teal-500/10 border-teal-500/20",
  },
  {
    key: "purchases",
    title: "Suppliers & Procurement",
    iconName: "Truck",
    description: "Supplier directories, purchase orders (PO), stock receiving & automated replenishment.",
    accent: "text-orange-500 bg-orange-500/10 border-orange-500/20",
  },
  {
    key: "reports",
    title: "Reports & Analytics",
    iconName: "BarChart3",
    description: "Daily sales summaries, top items, margin reports, scheduled digests & CSV/PDF exports.",
    accent: "text-indigo-500 bg-indigo-500/10 border-indigo-500/20",
  },
  {
    key: "team",
    title: "Team & Role Access (RBAC)",
    iconName: "Shield",
    description: "Staff accounts, granular role permissions (Cashier, Clerk, Manager, Owner) & audit logs.",
    accent: "text-rose-500 bg-rose-500/10 border-rose-500/20",
  },
  {
    key: "ecommerce",
    title: "Omnichannel & E-Commerce",
    iconName: "Globe",
    description: "1-Click Online Storefront, WhatsApp catalog sync, online orders & live POS alerts.",
    accent: "text-pink-500 bg-pink-500/10 border-pink-500/20",
  },
  {
    key: "enterprise",
    title: "Multi-Branch & Enterprise",
    iconName: "Layers",
    description: "Multi-branch store hierarchies, stock inter-transfers, white labeling & workflow rules.",
    accent: "text-purple-500 bg-purple-500/10 border-purple-500/20",
  },
  {
    key: "hardware",
    title: "Hardware & Offline PWA",
    iconName: "Cpu",
    description: "Offline-first PWA mode, weighing scales, cash drawers & customer facing secondary displays.",
    accent: "text-cyan-500 bg-cyan-500/10 border-cyan-500/20",
  },
  {
    key: "developer",
    title: "Developer API & Integrations",
    iconName: "Code2",
    description: "REST Webhook APIs, QuickBooks, Xero, Tally & third-party logistics integrations.",
    accent: "text-slate-500 bg-slate-500/10 border-slate-500/20",
  },
];

export const VERSION_ROADMAP_META = [
  {
    version: "v1" as const,
    title: "Version 1.0 — Rock-Solid Core MVP",
    badge: "Core Launch (V1.0)",
    focus: "Speed, Simplicity & Reliability",
    activeByDefault: true,
  },
  {
    version: "v2" as const,
    title: "Version 2.0 — Customer Retention & Store Growth",
    badge: "Growth (V2.0)",
    focus: "Sales Boost, Khata & Loyalty",
    activeByDefault: false,
  },
  {
    version: "v3" as const,
    title: "Version 3.0 — Smart Automation & Supply Chain",
    badge: "Automation (V3.0)",
    focus: "AI Forecasting & Expenses",
    activeByDefault: false,
  },
  {
    version: "v4" as const,
    title: "Version 4.0 — Omnichannel & E-Commerce Sync",
    badge: "Omnichannel (V4.0)",
    focus: "Selling Online & Offline Together",
    activeByDefault: false,
  },
  {
    version: "v5" as const,
    title: "Version 5.0 — Enterprise, Hardware & Ecosystem",
    badge: "Enterprise (V5.0)",
    focus: "Scale, Offline PWA & Integrations",
    activeByDefault: false,
  },
];

/**
 * Clean, structured Master Feature Catalog strictly organized by V1 to V5 Roadmap
 */
export const MASTER_FEATURE_CATALOG: FeatureModuleDefinition[] = [
  // ==========================================
  // 🟢 VERSION 1.0 (The Rock-Solid Core MVP) — DEFAULT ACTIVE
  // ==========================================
  {
    id: "feat-v1-pos-01",
    module_code: "F-POS-01",
    name: "Fast POS Terminal",
    function_group: "pos",
    group_title: "POS & Billing Terminal",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Fast barcode scan, Cash/Card checkout, Split payments, WhatsApp & Thermal receipt printing.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 8,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Checkout cart: 3 items ($45.00 total) -> Paid $50.00 cash",
      expected_output: "Change calculated: $5.00. 58mm/80mm Thermal & WhatsApp receipt generated.",
      simulated_payload: { cartItems: 3, total: 45.0, change: 5.0, status: "completed" },
    },
  },
  {
    id: "feat-v1-pos-02",
    module_code: "F-POS-02",
    name: "Barcode Hardware Scanner Support",
    function_group: "pos",
    group_title: "POS & Billing Terminal",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "USB & Bluetooth hardware barcode scanner support for instant product lookup in POS.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 10,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Scanner input: '8901030383829' + ENTER",
      expected_output: "Item 'Organic Green Tea 250g' detected and added to cart in <10ms.",
      simulated_payload: { barcode: "8901030383829", product: "Organic Green Tea 250g", price: 12.5 },
    },
  },
  {
    id: "feat-v1-pos-03",
    module_code: "F-POS-03",
    name: "Simple POS Returns & Refund",
    function_group: "pos",
    group_title: "POS & Billing Terminal",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "1-Click return & refund button at POS for quick customer order adjustments.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 12,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Return receipt #REC-9821: 1 unit damaged",
      expected_output: "Stock restored (+1 unit). Refund amount $15.00 credited back to customer.",
      simulated_payload: { receiptId: "REC-9821", refundAmount: 15.0, stockRestored: 1 },
    },
  },
  {
    id: "feat-v1-pos-04",
    module_code: "F-POS-04",
    name: "Flat & Percentage Order Discounts",
    function_group: "pos",
    group_title: "POS & Billing Terminal",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Instant percentage or flat dollar discounts applied directly to checkout cart.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 5,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Cart subtotal: $100.00 -> Apply 10% manager discount",
      expected_output: "Discount -$10.00 applied. Net payable total: $90.00.",
      simulated_payload: { subtotal: 100, discountPercent: 10, discountAmount: 10, total: 90 },
    },
  },
  {
    id: "feat-v1-inv-01",
    module_code: "F-INV-01",
    name: "Core Inventory & Stock Control",
    function_group: "inventory",
    group_title: "Inventory & Stock Control",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Product catalog, categories, stock in/out adjustments and movement history.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 14,
    source_file_url: "src/pages/user/UserInventory.tsx",
    test_scenario: {
      input_sample: "Product SKU: PRD-7820 -> Stock in +50 units (New shipment)",
      expected_output: "Stock updated from 45 -> 95 units. Audit trail movement logged.",
      simulated_payload: { sku: "PRD-7820", prevStock: 45, newStock: 95, delta: 50 },
    },
  },
  {
    id: "feat-v1-inv-02",
    module_code: "F-INV-02",
    name: "Low Stock & Out-of-Stock Alerts",
    function_group: "inventory",
    group_title: "Inventory & Stock Control",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Configurable threshold alerts (e.g. stock < 5) to prevent sudden stock-outs.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 15,
    source_file_url: "src/pages/user/UserInventory.tsx",
    test_scenario: {
      input_sample: "Current stock: 2 units (Threshold: 5 units)",
      expected_output: "Low stock badge triggered on dashboard and inventory view.",
      simulated_payload: { sku: "PRD-3301", current: 2, threshold: 5, alert: "LOW_STOCK" },
    },
  },
  {
    id: "feat-v1-ai-01",
    module_code: "F-AI-01",
    name: "Smart AI Product Autofill (Basic)",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Scan barcode or enter title to auto-suggest product name, category & standard pricing.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 60,
    source_file_url: "src/components/inventory/AIProductIntelligenceAssistant.tsx",
    test_scenario: {
      input_sample: "Barcode '8901030383829' or title 'Nescafe 200g'",
      expected_output: "AI auto-populates Category: 'Beverages/Coffee', Unit: 'pcs', Suggested Price: $8.50",
      simulated_payload: { name: "Nescafe Classic 200g", category: "Beverages", unit: "pcs", price: 8.5 },
    },
  },
  {
    id: "feat-v1-ai-analyst",
    module_code: "F-AI-ANALYST",
    name: "AI Assistant: Analyst Model",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Basic sales, profit & inventory intelligence. Answers real-time business health queries.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 45,
    source_file_url: "src/components/ai/AIAssistant.tsx",
    test_scenario: {
      input_sample: "Query: 'What is my gross profit today and low stock count?'",
      expected_output: "Analyst AI computes live DB analytics: Net Profit $450, Low stock: 3 items.",
      simulated_payload: { mode: "analyst", metricsAnswered: ["todayProfit", "lowStock"], status: "success" },
    },
  },
  {
    id: "feat-v1-ai-knowledge",
    module_code: "F-AI-KNOWLEDGE",
    name: "AI Assistant: Knowledge Model",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "GeFlow documentation, POS setup, barcode scanner troubleshooting and system FAQs.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 40,
    source_file_url: "src/components/ai/AIAssistant.tsx",
    test_scenario: {
      input_sample: "Query: 'How do I add a new cashier staff member?'",
      expected_output: "Knowledge AI explains step-by-step role assignment in Team Hub.",
      simulated_payload: { mode: "knowledge", topic: "RBAC_team_invite", status: "success" },
    },
  },
  {
    id: "feat-v2-ai-operator",
    module_code: "F-AI-OPERATOR",
    name: "AI Assistant: Operator Model",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Automated purchase drafting, stock-out reorder suggestions, and batch adjustments.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 90,
    source_file_url: "src/components/ai/AIAssistant.tsx",
    test_scenario: {
      input_sample: "Command: 'Draft a re-order PO for all items under threshold'",
      expected_output: "Operator AI compiles items and creates draft PO #PO-9812 for review.",
      simulated_payload: { mode: "operator", action: "draft_po", itemCount: 4 },
    },
  },
  {
    id: "feat-v3-ai-advisor",
    module_code: "F-AI-ADVISOR",
    name: "AI Assistant: Advisor Model",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Strategic margin recommendations, pricing elasticity, and predictive dead-stock warnings.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 120,
    source_file_url: "src/components/ai/AIAssistant.tsx",
    test_scenario: {
      input_sample: "Command: 'Analyze 30-day margins and suggest price optimization'",
      expected_output: "Advisor AI produces margin boost blueprint with projected +8% yield.",
      simulated_payload: { mode: "advisor", projectedYield: "+8%", itemsAnalyzed: 45 },
    },
  },
  {
    id: "feat-v1-ai-02",
    module_code: "F-AI-02",
    name: "1-Click AI Summary on Reports",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Generate 2-sentence executive summary of today's sales performance with 1 click.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 80,
    source_file_url: "src/pages/user/UserReports.tsx",
    test_scenario: {
      input_sample: "Today's sales: $2,450.00 across 84 transactions (Profit: $780.00)",
      expected_output: "AI Summary: 'Sales up 14% vs yesterday. Top performing category: Beverages. Margin at healthy 31.8%.'",
      simulated_payload: { summary: "Sales up 14% vs yesterday. Margin healthy at 31.8%.", tokens: 65 },
    },
  },
  {
    id: "feat-v1-team-01",
    module_code: "F-USR-01",
    name: "Team Roles & Permissions (RBAC)",
    function_group: "team",
    group_title: "Team & Role Access (RBAC)",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Role isolation: Cashier (Billing only), Inventory Clerk (Stock only), Store Owner/Manager.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 12,
    source_file_url: "src/pages/user/UserStaff.tsx",
    test_scenario: {
      input_sample: "User 'Ahmed' assigned role 'Cashier'",
      expected_output: "Access restricted to POS and own shifts. Admin/Settings routes locked.",
      simulated_payload: { role: "cashier", allowedRoutes: ["/pos", "/shifts"], status: "enforced" },
    },
  },
  {
    id: "feat-v1-rep-01",
    module_code: "F-REP-01",
    name: "Daily Sales & Profit Reports",
    function_group: "reports",
    group_title: "Reports & Analytics",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Daily sales totals, today's gross profit, top selling items, and PDF/CSV downloads.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 22,
    source_file_url: "src/pages/user/UserReports.tsx",
    test_scenario: {
      input_sample: "Query: Range 'Today' -> Generate PDF/CSV",
      expected_output: "Report compiled: 84 invoices, $2,450 revenue, $780 net profit. PDF ready.",
      simulated_payload: { totalSales: 2450, totalProfit: 780, exportFormat: "PDF/CSV" },
    },
  },
  {
    id: "feat-v1-ent-01",
    module_code: "F-COR-01",
    name: "Multi-Branch Store Structure",
    function_group: "enterprise",
    group_title: "Multi-Branch & Enterprise",
    version_target: "v1",
    version_title: "Version 1.0 — Core MVP",
    description: "Multi-branch store architecture: 1 store on Free, 5 on Standard, up to 10 on Premium.",
    lifecycle_phase: "live",
    global_active: true,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "optimal",
    latency_ms: 18,
    source_file_url: "src/pages/user/UserBranches.tsx",
    test_scenario: {
      input_sample: "Store switch: 'Main Branch' -> 'DHA Outlet'",
      expected_output: "Context switched instantly. Inventory and receipts scoped to selected branch.",
      simulated_payload: { activeBranch: "DHA Outlet", branchId: "br-02", isolation: "strict" },
    },
  },

  // ==========================================
  // 🔵 VERSION 2.0 (Customer Retention & Store Growth) — DEFAULT STAGED / DISABLED
  // ==========================================
  {
    id: "feat-v2-crm-01",
    module_code: "F-CRM-01",
    name: "Customer Loyalty Points & Store Credit",
    function_group: "crm",
    group_title: "Customer Khata & Loyalty",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Earn reward points on every purchase and redeem discounts at POS checkout.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 25,
    source_file_url: "src/pages/user/UserCustomers.tsx",
    test_scenario: {
      input_sample: "Customer spends $120.00 (Earning rate: 1 pt per $10)",
      expected_output: "12 loyalty points credited to customer wallet balance.",
      simulated_payload: { customerId: "CUST-104", pointsEarned: 12, balance: 145 },
    },
  },
  {
    id: "feat-v2-crm-02",
    module_code: "F-CRM-02",
    name: "Customer Khata / Ledger (Credit Sales)",
    function_group: "crm",
    group_title: "Customer Khata & Loyalty",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Udhaar / credit tracking for regular customers with automated balance reminders.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 22,
    source_file_url: "src/pages/user/UserCustomers.tsx",
    test_scenario: {
      input_sample: "Customer 'Rashid Khan' purchases $65.00 on Credit / Khata",
      expected_output: "Khata balance updated: $65.00 receivable. WhatsApp receipt with balance link generated.",
      simulated_payload: { customer: "Rashid Khan", creditAmount: 65, totalDue: 185 },
    },
  },
  {
    id: "feat-v2-pos-01",
    module_code: "F-MKT-01",
    name: "Coupon & Happy Hour Promo Engine",
    function_group: "pos",
    group_title: "POS & Billing Terminal",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Promo coupon codes, buy-1-get-1 rules, and automated scheduled happy hour discounts.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 18,
    source_file_url: "src/pages/user/UserCoupons.tsx",
    test_scenario: {
      input_sample: "Apply promo code 'SUMMER20' on $150 cart",
      expected_output: "20% discount validated ($30.00 saved). Net total: $120.00.",
      simulated_payload: { coupon: "SUMMER20", discount: 30, valid: true },
    },
  },
  {
    id: "feat-v2-ai-01",
    module_code: "F-AI-03",
    name: "Interactive AI Store Copilot (Chatbot)",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Natural language query assistant: 'Last month highest profit wala item konsa tha?'.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 110,
    source_file_url: "src/components/AiAssistantWidget.tsx",
    test_scenario: {
      input_sample: "Query: 'Which category gave me the highest margin last week?'",
      expected_output: "Copilot: 'Electronics led with 42.5% net margin, generating $1,420 net profit.'",
      simulated_payload: { responseTime: "110ms", tokens: 140, queryOk: true },
    },
  },
  {
    id: "feat-v2-ent-01",
    module_code: "F-INV-03",
    name: "Multi-Branch Inter-Store Transfers",
    function_group: "enterprise",
    group_title: "Multi-Branch & Enterprise",
    version_target: "v2",
    version_title: "Version 2.0 — Retention & Growth",
    description: "Transfer stock between branches with automated dispatch & receipt confirmation.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 30,
    source_file_url: "src/pages/user/UserTransfers.tsx",
    test_scenario: {
      input_sample: "Transfer 20 units of 'SKU-882' from Main Store -> Mall Branch",
      expected_output: "Transfer order #TR-401 created. Source stock deducted, in-transit state activated.",
      simulated_payload: { transferId: "TR-401", qty: 20, status: "in_transit" },
    },
  },

  // ==========================================
  // 🟣 VERSION 3.0 (Smart Automation & Supply Chain) — DEFAULT STAGED / DISABLED
  // ==========================================
  {
    id: "feat-v3-ai-01",
    module_code: "F-AI-04",
    name: "AI Predictive Demand & Stock Forecasting",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Analyzes past 90 days sales velocity to predict next week's item demand and restock date.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 140,
    source_file_url: "src/pages/user/UserAIInsights.tsx",
    test_scenario: {
      input_sample: "Run predictive model for SKU 'PRD-1029' (Daily avg velocity: 6.4 units)",
      expected_output: "Forecast: Stock depletion in 4 days. Recommended reorder: 50 units by Thursday.",
      simulated_payload: { predictedDaysLeft: 4, reorderQty: 50, confidence: "94%" },
    },
  },
  {
    id: "feat-v3-pur-01",
    module_code: "F-PUR-01",
    name: "Automated Purchase Orders & Supplier Dispatch",
    function_group: "purchases",
    group_title: "Suppliers & Procurement",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Automated PO generation and 1-click email/WhatsApp dispatch to vendors when stock is low.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 35,
    source_file_url: "src/pages/user/UserPurchases.tsx",
    test_scenario: {
      input_sample: "Trigger auto PO for vendor 'Al-Madina Traders' (5 low stock items)",
      expected_output: "Purchase Order #PO-8812 compiled. PDF dispatch queued to vendor email.",
      simulated_payload: { poNumber: "PO-8812", totalItems: 5, totalCost: 1240.0 },
    },
  },
  {
    id: "feat-v3-fin-01",
    module_code: "F-FIN-01",
    name: "Comprehensive Expense & Overhead Tracking",
    function_group: "finance",
    group_title: "Finance, Profit & Expenses",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Log store rent, electricity, staff salaries, and operational costs for True Net Profit.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 20,
    source_file_url: "src/pages/user/UserExpenses.tsx",
    test_scenario: {
      input_sample: "Log expense: $450.00 'Electricity Bill' (Category: Utilities)",
      expected_output: "Expense logged. Monthly Net Profit adjusted from $3,400 -> $2,950.",
      simulated_payload: { category: "Utilities", amount: 450, netProfitAdjusted: 2950 },
    },
  },
  {
    id: "feat-v3-rep-01",
    module_code: "F-REP-02",
    name: "Scheduled Morning Sales Email/WhatsApp Digest",
    function_group: "reports",
    group_title: "Reports & Analytics",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Daily automated 9:00 AM briefing sent directly to store owner's WhatsApp / Email.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 45,
    source_file_url: "src/pages/user/UserReports.tsx",
    test_scenario: {
      input_sample: "Cron 09:00 AM daily trigger for Owner (+923001234567)",
      expected_output: "Digest dispatched: 'Yesterday's Gross: $3,210 | Profit: $980 | Top item: Milk 1L'",
      simulated_payload: { status: "dispatched", channel: "WhatsApp/Email", timestamp: "09:00:02" },
    },
  },
  {
    id: "feat-v3-inv-01",
    module_code: "F-INV-04",
    name: "Barcode Sticker & Thermal Label Designer",
    function_group: "inventory",
    group_title: "Inventory & Stock Control",
    version_target: "v3",
    version_title: "Version 3.0 — Smart Automation",
    description: "Design and batch-print custom price tag stickers & barcode labels on thermal printers.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 25,
    source_file_url: "src/pages/user/UserInventory.tsx",
    test_scenario: {
      input_sample: "Generate 50 barcode labels for SKU 'PRD-9901' (Format: 50x25mm)",
      expected_output: "Print vector ready. Code128 barcode with price and store logo rendered.",
      simulated_payload: { sku: "PRD-9901", labelCount: 50, format: "50x25mm" },
    },
  },

  // ==========================================
  // 🟡 VERSION 4.0 (Omnichannel & E-Commerce Sync) — DEFAULT STAGED / DISABLED
  // ==========================================
  {
    id: "feat-v4-eco-01",
    module_code: "F-ECO-01",
    name: "1-Click Online Storefront & WhatsApp Catalog",
    function_group: "ecommerce",
    group_title: "Omnichannel & E-Commerce",
    version_target: "v4",
    version_title: "Version 4.0 — Omnichannel",
    description: "Instantly turn POS inventory into a customer-facing digital web catalog and WhatsApp store.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 50,
    source_file_url: "src/pages/user/UserStorefront.tsx",
    test_scenario: {
      input_sample: "Publish 120 inventory items to public storefront domain 'mystore.geflow.com'",
      expected_output: "Digital storefront live. Sync webhook connected to POS live inventory.",
      simulated_payload: { publishedItems: 120, storefrontUrl: "mystore.geflow.com", status: "online" },
    },
  },
  {
    id: "feat-v4-eco-02",
    module_code: "F-ECO-02",
    name: "Live Online Order Pop-up in POS",
    function_group: "ecommerce",
    group_title: "Omnichannel & E-Commerce",
    version_target: "v4",
    version_title: "Version 4.0 — Omnichannel",
    description: "Online orders from web/WhatsApp pop up in real-time on POS screen with sound alert.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 15,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Customer places $35 order via WhatsApp Store",
      expected_output: "POS audio chime plays. New order badge appears with 'Accept & Print KOT' action.",
      simulated_payload: { orderId: "ORD-902", total: 35.0, source: "WhatsApp", alertPlayed: true },
    },
  },
  {
    id: "feat-v4-fin-01",
    module_code: "F-FIN-02",
    name: "Multi-Currency & International Tax Engine",
    function_group: "finance",
    group_title: "Finance, Profit & Expenses",
    version_target: "v4",
    version_title: "Version 4.0 — Omnichannel",
    description: "Compliant tax calculation (ZATCA e-invoicing for KSA, UAE FTA VAT, GST for India, US Sales Tax).",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 18,
    source_file_url: "src/pages/user/UserSettings.tsx",
    test_scenario: {
      input_sample: "KSA region selected -> Generate ZATCA Phase 2 compliant QR code",
      expected_output: "TLV encoded Base64 QR code embedded into receipt footer successfully.",
      simulated_payload: { standard: "ZATCA_KSA_PHASE2", vatPercent: 15, qrValid: true },
    },
  },
  {
    id: "feat-v4-ai-01",
    module_code: "F-AI-05",
    name: "AI Invoice Vision OCR Import",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v4",
    version_title: "Version 4.0 — Omnichannel",
    description: "Upload photo/PDF of paper supplier invoice to automatically extract items, qty & prices.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 220,
    source_file_url: "src/pages/user/UserPurchases.tsx",
    test_scenario: {
      input_sample: "Upload paper invoice JPEG (14 line items from Nestle)",
      expected_output: "14 products recognized with unit costs. Stock ready for 1-click receiving.",
      simulated_payload: { itemsExtracted: 14, confidence: "98.2%", totalRecognized: 3450.0 },
    },
  },
  {
    id: "feat-v4-ai-02",
    module_code: "F-AI-06",
    name: "AI Multi-Lingual Interface (10+ Languages)",
    function_group: "ai",
    group_title: "AI & Smart Automation",
    version_target: "v4",
    version_title: "Version 4.0 — Omnichannel",
    description: "Automatic localized translation for Arabic, Urdu, Spanish, French, German, and Turkish.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: true,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 20,
    source_file_url: "src/components/LanguageSelector.tsx",
    test_scenario: {
      input_sample: "Locale switch: 'en' -> 'ar' (Arabic RTL)",
      expected_output: "Interface transforms into full RTL with accurate retail nomenclature.",
      simulated_payload: { lang: "ar", dir: "rtl", status: "translated" },
    },
  },

  // ==========================================
  // 🔴 VERSION 5.0 (Enterprise, Hardware & Open Ecosystem) — DEFAULT STAGED / DISABLED
  // ==========================================
  {
    id: "feat-v5-hdw-01",
    module_code: "F-HDW-01",
    name: "Direct Hardware Integration (Scales & Customer Displays)",
    function_group: "hardware",
    group_title: "Hardware & Offline PWA",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Direct RS232/USB connection for electronic weighing scales, cash drawers & dual customer monitors.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 10,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Electronic scale sends weight payload: 1.450 kg for SKU 'Apples'",
      expected_output: "POS calculates price: 1.450kg * $3.00/kg = $4.35 instantly.",
      simulated_payload: { weightKg: 1.45, pricePerKg: 3.0, total: 4.35, port: "COM3" },
    },
  },
  {
    id: "feat-v5-hdw-02",
    module_code: "F-HDW-02",
    name: "Offline-First PWA & Desktop App with Auto-Sync",
    function_group: "hardware",
    group_title: "Hardware & Offline PWA",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Keep billing customers seamlessly even if internet drops; auto-syncs when online.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: true,
    plan_premium: true,
    health: "high",
    latency_ms: 5,
    source_file_url: "src/pages/user/UserPOS.tsx",
    test_scenario: {
      input_sample: "Network disconnects -> Process 12 cash sales offline",
      expected_output: "Sales stored in IndexedDB. Internet restored -> 12 sales synced with 0 conflicts.",
      simulated_payload: { offlineSales: 12, syncResult: "synced_successfully" },
    },
  },
  {
    id: "feat-v5-dev-01",
    module_code: "F-DEV-01",
    name: "Public REST Developer API & Webhooks",
    function_group: "developer",
    group_title: "Developer API & Integrations",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Connect custom ERPs, Shopify, WooCommerce, and courier delivery tracking apps.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 12,
    source_file_url: "src/pages/admin/AdminApi.tsx",
    test_scenario: {
      input_sample: "POST /api/v1/orders with Bearer token",
      expected_output: "Order accepted (HTTP 201 Created). Webhook 'order.created' fired.",
      simulated_payload: { endpoint: "/api/v1/orders", status: 201, auth: "bearer_ok" },
    },
  },
  {
    id: "feat-v5-dev-02",
    module_code: "F-INT-01",
    name: "Accounting Software Sync (QuickBooks / Xero)",
    function_group: "developer",
    group_title: "Developer API & Integrations",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Automatic end-of-day journal sync with QuickBooks, Xero, and Tally accounting ledger.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 85,
    source_file_url: "src/pages/user/UserSettings.tsx",
    test_scenario: {
      input_sample: "End-of-day sync: $4,500 sales + $1,200 COGS -> Sync to QuickBooks",
      expected_output: "Journal entry #JE-901 posted to QuickBooks Online account with 0 errors.",
      simulated_payload: { accountingService: "QuickBooks", status: "synced", jeNumber: "JE-901" },
    },
  },
  {
    id: "feat-v5-ent-01",
    module_code: "F-ENT-02",
    name: "Enterprise Multi-Warehouse Hierarchy",
    function_group: "enterprise",
    group_title: "Multi-Branch & Enterprise",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Central regional distribution warehouses supplying multiple subsidiary retail stores.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 30,
    source_file_url: "src/pages/user/UserBranches.tsx",
    test_scenario: {
      input_sample: "Central Warehouse dispatches 500 crates across 4 regional branches",
      expected_output: "Consolidated dispatch manifest generated with tracking numbers.",
      simulated_payload: { branchesSupplied: 4, totalCrates: 500, status: "dispatched" },
    },
  },
  {
    id: "feat-v5-ent-02",
    module_code: "F-ENT-03",
    name: "White Label & Custom Domain Branding",
    function_group: "enterprise",
    group_title: "Multi-Branch & Enterprise",
    version_target: "v5",
    version_title: "Version 5.0 — Enterprise Ecosystem",
    description: "Custom domain, custom brand logos, custom invoice color templates and removed GeFlow branding.",
    lifecycle_phase: "staging",
    global_active: false,
    plan_free: false,
    plan_standard: false,
    plan_premium: true,
    health: "high",
    latency_ms: 10,
    source_file_url: "src/pages/admin/AdminWhiteLabel.tsx",
    test_scenario: {
      input_sample: "Custom domain mapped: 'pos.martsuper.com' with custom SVG logo",
      expected_output: "SSL certificate provisioned and custom themes loaded across app.",
      simulated_payload: { domain: "pos.martsuper.com", theme: "Custom Brand", ssl: "active" },
    },
  },
];

const STORAGE_KEY = "geflow_platform_feature_modules_v4";

/**
 * Reads the local features list or initializes with V1 default active catalog
 */
export const getLocalFeatureCatalog = (): FeatureModuleDefinition[] => {
  if (typeof window === "undefined") return MASTER_FEATURE_CATALOG;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(MASTER_FEATURE_CATALOG));
      return MASTER_FEATURE_CATALOG;
    }
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      // Merge with master catalog so scenarios and group metadata stay up to date
      return MASTER_FEATURE_CATALOG.map((masterItem) => {
        const stored = parsed.find((p: any) => p.module_code === masterItem.module_code || p.id === masterItem.id);
        if (stored) {
          return {
            ...masterItem,
            global_active: stored.global_active,
            lifecycle_phase: stored.lifecycle_phase ?? masterItem.lifecycle_phase,
            plan_free: stored.plan_free ?? masterItem.plan_free,
            plan_standard: stored.plan_standard ?? masterItem.plan_standard,
            plan_premium: stored.plan_premium ?? masterItem.plan_premium,
          };
        }
        return masterItem;
      });
    }
  } catch (e) {
    console.warn("Failed to read feature catalog storage:", e);
  }
  return MASTER_FEATURE_CATALOG;
};

/**
 * Saves feature definitions to persistent storage and triggers cross-tab updates
 */
export const saveLocalFeatureCatalog = (items: FeatureModuleDefinition[]) => {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
    window.dispatchEvent(new Event("storage"));
  } catch (e) {
    console.warn("Failed to save feature catalog:", e);
  }
};
