import { LogItem } from "@/types/logs";

export const INITIAL_SYSTEM_SERVICES = [
  { name: "Database (Supabase PostgreSQL)", status: "healthy", latency: 18, uptime: "99.99%", version: "15.1" },
  { name: "GeCore AI System Engine Gateway", status: "healthy", latency: 185, uptime: "99.98%", version: "v3.2" },
  { name: "Authentication Service", status: "healthy", latency: 32, uptime: "99.98%", version: "v2.1" },
  { name: "Payments Engine (Stripe/PayPal)", status: "healthy", latency: 110, uptime: "99.99%", version: "v3.0" },
  { name: "Cloud Storage Bucket", status: "healthy", latency: 45, uptime: "99.99%", version: "S3-compat" },
  { name: "Realtime WebSocket Hub", status: "healthy", latency: 12, uptime: "99.95%", version: "v1.8" },
  { name: "Email Relay (Resend / SMTP)", status: "healthy", latency: 140, uptime: "99.91%", version: "v2.0" },
  { name: "Background Cron Scheduler", status: "healthy", latency: 5, uptime: "100%", version: "v1.2" },
];

export const INITIAL_AI_MODELS = [
  { name: "GeCore AI Analytics Engine", provider: "GeCore AI System Engine", requests: 7420, latency: "0.5s", successRate: "99.8%", status: "healthy", cost: "$0.00" },
  { name: "GeCore AI Real-Time Agent", provider: "GeCore AI System Engine", requests: 5120, latency: "0.3s", successRate: "99.9%", status: "healthy", cost: "$0.00" },
  { name: "GeCore AI Natural Language Synthesizer", provider: "GeCore AI System Engine", requests: 2150, latency: "0.6s", successRate: "99.5%", status: "healthy", cost: "$0.00" },
  { name: "GeCore AI Strategic Advisor", provider: "GeCore AI System Engine", requests: 840, latency: "0.8s", successRate: "99.7%", status: "healthy", cost: "$0.00" },
];

export const generateEnterpriseLogs = (): LogItem[] => {
  const now = Date.now();
  const subMinutes = (m: number) => new Date(now - m * 60 * 1000).toISOString();

  return [
    // 1. Critical System / Error Log
    {
      id: "LOG-98241",
      timestamp: subMinutes(2),
      module: "Payments",
      event: "Stripe Webhook Delayed",
      category: "payments",
      severity: "warning",
      status: "investigating",
      business: { name: "Apex Global Wholesale", plan: "premium", status: "active" },
      user: { name: "Sarah Jenkins", email: "sarah@apexwholesale.com" },
      ip: "192.0.2.45",
      country: "United States",
      countryCode: "US",
      browser: "Chrome 124",
      os: "macOS Sonoma",
      device: "desktop",
      description: "Webhook delivery for subscription upgrade invoice INV-2054 delayed by 4.2 seconds due to network handshake retry.",
      paymentData: {
        gateway: "stripe",
        method: "Visa •••• 4242",
        amount: 79.0,
        currency: "USD",
        transactionId: "ch_3N8vKxLkdIwHu4g1",
        invoiceNumber: "INV-2054",
        fee: 2.59,
        failureReason: "Gateway Timeout Retry",
      },
      timeline: [
        { time: "09:20:00", title: "Customer submitted checkout", desc: "Selected Annual Premium tier" },
        { time: "09:20:02", title: "Stripe charge authorized", desc: "Status set to succeeded" },
        { time: "09:20:04", title: "Webhook handshake retried", desc: "Resolved on second attempt" },
      ],
      relatedRecord: { type: "invoice", id: "INV-2054", title: "Invoice #2054 ($79.00)" },
    },

    // 2. AI Forecast Log
    {
      id: "LOG-98240",
      timestamp: subMinutes(5),
      module: "AI Assistant",
      event: "AI Stock Forecast Generated",
      category: "ai",
      severity: "info",
      status: "success",
      business: { name: "Downtown Mart & Pharmacy", plan: "standard", status: "active" },
      user: { name: "Bilal Ahmed", email: "bilal@downtownmart.pk" },
      ip: "39.40.12.188",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Firefox 125",
      os: "Windows 11",
      device: "desktop",
      description: "Generated 30-day replenishment demand prediction for 48 pharmaceuticals using GeCore AI System Engine.",
      aiData: {
        feature: "AI Inventory Forecast",
        model: "GeCore AI Demand Predictor",
        provider: "GeCore AI System Engine",
        latencyMs: 440,
        promptTokens: 1420,
        completionTokens: 620,
        totalTokens: 2040,
        estimatedCost: 0.00,
        promptText: "Analyze past 6 months sales spikes and seasonal monsoon trends for Antibiotics & Paracetamol SKU list...",
        responseText: "Predicted surge: +34% in week 3. Reordering recommendation: 250 units minimum safe threshold.",
        requestId: "req_ai_991823",
      },
      timeline: [
        { time: "09:15:10", title: "Forecast requested from POS dashboard" },
        { time: "09:15:11", title: "Context vectorized and dispatched to GeCore AI System Engine" },
        { time: "09:15:12", title: "Response parsed and cache updated" },
      ],
      relatedRecord: { type: "report", id: "REP-882", title: "Pharmaceutical Demand Forecast" },
    },

    // 3. User Activity Log
    {
      id: "LOG-98239",
      timestamp: subMinutes(8),
      module: "Products",
      event: "Product Created",
      category: "user_activity",
      severity: "info",
      status: "success",
      business: { name: "City Electronics Hub", plan: "premium", status: "active" },
      user: { name: "Hamza Tariq", email: "hamza@cityelectronics.com" },
      ip: "182.180.98.12",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Chrome 123",
      os: "Windows 11",
      device: "desktop",
      description: "Added new SKU 'Ultra Wireless Barcode Scanner Gen 3' with barcode '890123984712'.",
      userActivityData: {
        actionType: "create",
        affectedRecordName: "Ultra Wireless Barcode Scanner Gen 3",
        recordType: "Product",
        duration: "1.4s",
      },
      timeline: [
        { time: "09:12:00", title: "Clicked New Product button" },
        { time: "09:12:15", title: "Uploaded product image and set wholesale price $45" },
        { time: "09:12:18", title: "Saved to inventory database" },
      ],
      relatedRecord: { type: "product", id: "PRD-9014", title: "Ultra Wireless Scanner Gen 3" },
    },

    // 4. Security Critical Threat Log
    {
      id: "LOG-98238",
      timestamp: subMinutes(12),
      module: "Security",
      event: "Suspicious Login Attempt Blocked",
      category: "security",
      severity: "critical",
      status: "blocked",
      business: { name: "MedTech Dispensary", plan: "standard", status: "active" },
      user: { name: "Unknown / Attacker", email: "admin@medtech.com" },
      ip: "185.220.101.5",
      country: "Russia",
      countryCode: "RU",
      browser: "Headless Chrome / Curl",
      os: "Linux",
      device: "desktop",
      description: "Triggered Brute Force Protection rule: 8 failed login attempts within 45 seconds from high-risk IP subnet.",
      securityData: {
        threatType: "Credential Stuffing / Brute Force",
        riskScore: 96,
        detectionMethod: "Automated Rate Limiter & Geo-Anomaly Rule",
        isBlocked: true,
        isAccountLocked: false,
        recommendedAction: "Keep IP block active for 7 days. Enforce MFA on target account.",
      },
      timeline: [
        { time: "09:08:01", title: "Initial login attempt with invalid password" },
        { time: "09:08:14", title: "5th rapid attempt detected" },
        { time: "09:08:45", title: "Rule SEC-801 fired: IP temporarily blacklisted" },
      ],
    },

    // 5. Business Activity Log
    {
      id: "LOG-98237",
      timestamp: subMinutes(15),
      module: "Sales",
      event: "POS Sale Completed",
      category: "business_activity",
      severity: "info",
      status: "completed",
      business: { name: "Green Valley Grocers", plan: "lifetime", status: "active" },
      user: { name: "Fatima Noor", email: "fatima@greenvalley.com" },
      ip: "110.39.4.120",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Chrome Mobile",
      os: "Android 14",
      device: "tablet",
      description: "Completed in-store POS checkout of 6 items total $142.50 via Cash tender.",
      businessActivityData: {
        actionName: "POS Sale Completed",
        moduleName: "Sales",
        performedBy: "Fatima Noor",
        activityVolumeToday: 184,
        planStatus: "lifetime",
      },
      timeline: [
        { time: "09:05:00", title: "Items scanned into POS cart" },
        { time: "09:05:22", title: "Cash received $150.00, change returned $7.50" },
        { time: "09:05:24", title: "Thermal receipt printed & stock decremented" },
      ],
      relatedRecord: { type: "sale", id: "SALE-4912", title: "POS Receipt #4912 ($142.50)" },
    },

    // 6. Billing Log - Plan Upgraded
    {
      id: "LOG-98236",
      timestamp: subMinutes(22),
      module: "Billing",
      event: "Plan Upgraded to Premium",
      category: "billing",
      severity: "info",
      status: "success",
      business: { name: "Oasis Superstore", plan: "premium", status: "active" },
      user: { name: "Rashid Mahmood", email: "rashid@oasissuperstore.com" },
      ip: "175.107.199.14",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Edge 124",
      os: "Windows 11",
      device: "desktop",
      description: "Business upgraded workspace tier from Standard ($29) to Premium ($79) annual billing.",
      billingData: {
        plan: "Premium Tier",
        invoiceNumber: "INV-2053",
        amount: 790.0,
        currency: "USD",
        billingCycle: "Annual (20% Off)",
        renewalDate: "2027-08-14",
        couponCode: "SUMMER20",
      },
      timeline: [
        { time: "08:58:00", title: "User selected Annual Premium plan on Checkout" },
        { time: "08:58:12", title: "Applied promo coupon SUMMER20 (-20%)" },
        { time: "08:58:30", title: "Payment authorized and profile limits adjusted" },
      ],
      relatedRecord: { type: "invoice", id: "INV-2053", title: "Invoice #2053 ($790.00)" },
    },

    // 7. Error Log - Rate Limit Exceeded
    {
      id: "LOG-98235",
      timestamp: subMinutes(30),
      module: "AI Assistant",
      event: "AI Rate Limit 429",
      category: "errors",
      severity: "medium",
      status: "resolved",
      business: { name: "Apex Retail Global Ltd", plan: "standard", status: "active" },
      user: { name: "Marcus Vance", email: "marcus@apexretailglobal.com" },
      ip: "198.51.100.42",
      country: "United States",
      countryCode: "US",
      browser: "Chrome 124",
      os: "macOS Sonoma",
      device: "desktop",
      description: "AI workload auto-scaled seamlessly via GeCore AI Failover Router.",
      errorData: {
        errorType: "HTTP 429 RateLimitExceeded",
        errorCode: 429,
        sourceFile: "src/lib/geCoreAiEngine.ts",
        line: 142,
        isRetryable: true,
        isResolved: true,
        resolutionNote: "Automatic routing to GeCore AI System Engine secondary node succeeded in 120ms.",
        stackTrace: "Error: High load balanced\n    at dispatchAIRequest (src/lib/geCoreAiEngine.ts:142:12)\n    at processDemandForecast (src/components/ai/AIAssistant.tsx:88:9)",
      },
      timeline: [
        { time: "08:50:00", title: "High concurrency request burst (42 concurrent queries)" },
        { time: "08:50:01", title: "Provider returned 429" },
        { time: "08:50:02", title: "GeFlow Failover Router switched target model" },
      ],
    },

    // 8. Auth Log - Passwordless Magic Link Login
    {
      id: "LOG-98234",
      timestamp: subMinutes(35),
      module: "Authentication",
      event: "User Login (Magic Link)",
      category: "auth",
      severity: "info",
      status: "success",
      business: { name: "Al-Faisal Textiles", plan: "standard", status: "active" },
      user: { name: "Faisal Rehman", email: "faisal@alfaisal.com" },
      ip: "182.185.12.90",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Chrome 124",
      os: "Windows 11",
      device: "desktop",
      description: "Successfully authenticated via email one-time token authorization.",
      authData: {
        action: "login",
        method: "magic_link",
        sessionId: "sess_918239a01",
        sessionDuration: "45 mins",
        expiresAt: "2026-08-15T10:00:00Z",
      },
      timeline: [
        { time: "08:45:00", title: "Requested 1-click magic sign in link" },
        { time: "08:45:15", title: "Clicked verification link in Gmail" },
        { time: "08:45:18", title: "Session cookies granted and dashboard loaded" },
      ],
      relatedRecord: { type: "user", id: "USR-401", title: "Faisal Rehman (faisal@alfaisal.com)" },
    },

    // 9. System Log - Database Health Check
    {
      id: "LOG-98233",
      timestamp: subMinutes(42),
      module: "System",
      event: "Database Vacuum & Index Optimized",
      category: "system",
      severity: "info",
      status: "healthy",
      description: "Automated Supabase database maintenance completed in 2.1s with 18ms query latency average.",
      systemData: {
        serviceName: "Database (Supabase PostgreSQL)",
        latencyMs: 18,
        version: "v15.1",
        cpuPercent: 12,
        memoryPercent: 28,
        uptime: "99.99%",
      },
      timeline: [
        { time: "08:38:00", title: "Nightly auto-vacuum worker started" },
        { time: "08:38:02", title: "Indexes rebuilt for products and pos_sales tables" },
        { time: "08:38:03", title: "Resource metrics reported nominal" },
      ],
    },

    // 10. Security - Permission Role Updated
    {
      id: "LOG-98232",
      timestamp: subMinutes(50),
      module: "Security",
      event: "User Role Promoted to Admin",
      category: "security",
      severity: "medium",
      status: "success",
      business: { name: "Apex Global Wholesale", plan: "premium", status: "active" },
      user: { name: "Sarah Jenkins", email: "sarah@apexwholesale.com" },
      ip: "192.0.2.45",
      country: "United States",
      countryCode: "US",
      browser: "Chrome 124",
      os: "macOS Sonoma",
      device: "desktop",
      description: "Super Admin assigned 'Store Manager' role to employee Kamran Liaquat.",
      securityData: {
        threatType: "Permission Escalation (Audit)",
        riskScore: 25,
        detectionMethod: "Administrative Audit Trail",
      },
      timeline: [
        { time: "08:30:00", title: "Owner opened Team Hub settings" },
        { time: "08:30:20", title: "Assigned POS Cashier + Inventory Editor permissions" },
        { time: "08:30:22", title: "Audit log recorded" },
      ],
      relatedRecord: { type: "user", id: "USR-772", title: "Kamran Liaquat" },
    },

    // 11. Payments - Refund Processed
    {
      id: "LOG-98231",
      timestamp: subMinutes(65),
      module: "Payments",
      event: "Payment Refunded",
      category: "payments",
      severity: "low",
      status: "completed",
      business: { name: "City Cafe & Bistro", plan: "standard", status: "active" },
      user: { name: "Adnan Shah", email: "adnan@citycafe.pk" },
      ip: "39.50.21.14",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Safari 17",
      os: "iOS 17.4",
      device: "mobile",
      description: "Processed refund of $29.00 USD for unused subscription period per customer request.",
      paymentData: {
        gateway: "paypal",
        method: "PayPal Account",
        amount: 29.0,
        currency: "USD",
        transactionId: "pp_refund_8912739",
        invoiceNumber: "INV-1988",
        fee: 0,
      },
      timeline: [
        { time: "08:15:00", title: "Refund request submitted through Admin Portal" },
        { time: "08:15:30", title: "PayPal API refunded balance" },
        { time: "08:15:32", title: "Confirmation receipt dispatched to user" },
      ],
      relatedRecord: { type: "invoice", id: "INV-1988", title: "Invoice #1988" },
    },

    // 12. User Activity - Purchase Order Created
    {
      id: "LOG-98230",
      timestamp: subMinutes(80),
      module: "Purchases",
      event: "Purchase Order Created",
      category: "user_activity",
      severity: "info",
      status: "success",
      business: { name: "Downtown Mart & Pharmacy", plan: "standard", status: "active" },
      user: { name: "Bilal Ahmed", email: "bilal@downtownmart.pk" },
      ip: "39.40.12.188",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Chrome 124",
      os: "Windows 11",
      device: "desktop",
      description: "Created bulk purchase order PO-1092 from supplier 'National Distributors Ltd' ($2,450.00).",
      userActivityData: {
        actionType: "create",
        affectedRecordName: "PO-1092 Bulk Pharmaceuticals",
        recordType: "Purchase Order",
        duration: "3.2s",
      },
      relatedRecord: { type: "purchase", id: "PO-1092", title: "PO-1092 ($2,450.00)" },
    },

    // 13. System - Background Cron Worker
    {
      id: "LOG-98229",
      timestamp: subMinutes(95),
      module: "System",
      event: "Low Stock Alerts Synced",
      category: "system",
      severity: "info",
      status: "healthy",
      description: "Processed 128 active businesses; dispatched 8 low stock email digests to store owners.",
      systemData: {
        serviceName: "Background Cron Scheduler",
        latencyMs: 120,
        version: "v1.2",
        uptime: "100%",
      },
    },

    // 14. AI Assistant - Receipt OCR Analysis
    {
      id: "LOG-98228",
      timestamp: subMinutes(110),
      module: "AI Assistant",
      event: "Receipt OCR Scan Processed",
      category: "ai",
      severity: "info",
      status: "success",
      business: { name: "Fresh Produce Mart", plan: "premium", status: "active" },
      user: { name: "Tariq Mehmood", email: "tariq@freshproduce.com" },
      ip: "182.180.20.11",
      country: "Pakistan",
      countryCode: "PK",
      browser: "Chrome 124",
      os: "macOS Sonoma",
      device: "desktop",
      description: "Extracted 14 item rows and tax values from supplier invoice image using GeCore AI Vision in 0.8s.",
      aiData: {
        feature: "AI Receipt Scanner",
        model: "GeCore AI Vision Engine",
        provider: "GeCore AI System Engine",
        latencyMs: 820,
        promptTokens: 2840,
        completionTokens: 410,
        totalTokens: 3250,
        estimatedCost: 0.00,
        promptText: "[Image Input: scanned_supplier_bill.jpg] Extract table of items, quantities, and cost...",
        responseText: "Extracted 14 items. Total match: $1,420.50. Confidence score: 99.4%.",
        requestId: "req_ocr_882194",
      },
    },

    // 15. Security - Blocked IP Event
    {
      id: "LOG-98227",
      timestamp: subMinutes(130),
      module: "Security",
      event: "SQL Injection Probe Blocked",
      category: "security",
      severity: "high",
      status: "blocked",
      user: { name: "Blocked Crawler", email: "crawler@scanner-bot.net" },
      ip: "45.155.205.233",
      country: "Netherlands",
      countryCode: "NL",
      browser: "Python Requests / Wget",
      os: "Linux",
      device: "desktop",
      description: "Blocked malformed URI query containing UNION SELECT syntax at WAF gateway layer.",
      securityData: {
        threatType: "WAF SQL Injection Attempt",
        riskScore: 98,
        detectionMethod: "Cloudflare / Reverse Proxy Filter",
        isBlocked: true,
      },
    },
  ];
};
