import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";

/**
 * AI-powered support auto-reply.
 * Finds open tickets that have received NO admin/support reply within the
 * configured threshold (ai_auto_reply_after_hours) and posts a best-guess
 * reply generated by the Lovable AI gateway. Intended to be run on a cron.
 */
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const { data: settings } = await supabase
      .from("support_automation_settings")
      .select("*")
      .limit(1)
      .maybeSingle();

    if (!settings?.ai_auto_reply_enabled) {
      return json({ skipped: "AI auto-reply disabled" });
    }

    const hours = Number(settings.ai_auto_reply_after_hours) || 24;
    const cutoff = new Date(Date.now() - hours * 3600_000).toISOString();

    // Candidate tickets: open/pending, created before cutoff.
    const { data: tickets } = await supabase
      .from("support_tickets")
      .select("id, subject, category, priority, created_at, owner_user_id")
      .in("status", ["open", "pending"])
      .lte("created_at", cutoff)
      .limit(25);

    if (!tickets?.length) return json({ processed: 0 });

    // Pick an admin author for the reply.
    const { data: adminRole } = await supabase
      .from("user_roles")
      .select("user_id")
      .eq("role", "admin")
      .limit(1)
      .maybeSingle();

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    let processed = 0;

    for (const t of tickets) {
      const { data: msgs } = await supabase
        .from("ticket_messages")
        .select("id, is_admin, body, created_at")
        .eq("ticket_id", t.id)
        .order("created_at", { ascending: true });

      const hasAdminReply = (msgs ?? []).some((m) => m.is_admin);
      if (hasAdminReply) continue; // a human/auto reply already exists

      // Skip if the most recent message is already older than the threshold check
      const conversation = (msgs ?? [])
        .map((m) => `${m.is_admin ? "Support" : "Customer"}: ${m.body}`)
        .join("\n");

      let replyBody =
        "Thanks for reaching out. Our team is reviewing your ticket and will follow up shortly with a detailed response.";

      if (LOVABLE_API_KEY) {
        try {
          const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${LOVABLE_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model: "google/gemini-2.5-flash",
              messages: [
                {
                  role: "system",
                  content:
                    "You are a helpful, concise SaaS support agent for GeFlow, a business inventory & POS platform. Write a warm, professional first reply to the customer's ticket. Acknowledge their issue, give a helpful next step or workaround, and reassure them. Keep it under 120 words. Do not invent account-specific details.",
                },
                {
                  role: "user",
                  content: `Ticket subject: ${t.subject}\nCategory: ${t.category}\nPriority: ${t.priority}\n\nConversation so far:\n${conversation}`,
                },
              ],
            }),
          });
          if (aiRes.ok) {
            const j = await aiRes.json();
            const c = j?.choices?.[0]?.message?.content;
            if (c && typeof c === "string") replyBody = c.trim();
          }
        } catch (_e) {
          // fall back to default replyBody
        }
      }

      await supabase.from("ticket_messages").insert({
        ticket_id: t.id,
        author_user_id: adminRole?.user_id ?? t.owner_user_id,
        is_admin: true,
        body: replyBody,
      });
      // Move the ticket to pending so it's not re-processed.
      await supabase.from("support_tickets").update({ status: "pending" }).eq("id", t.id);
      processed++;
    }

    return json({ processed });
  } catch (e) {
    return json({ error: String(e) }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    headers: { ...corsHeaders, "Content-Type": "application/json" },
    status,
  });
}
