import { CanonicalField, CanonicalFieldDefinition } from "./types";

export const CANONICAL_FIELDS: CanonicalFieldDefinition[] = [
  {
    key: "name",
    label: "Product Name",
    description: "Primary product identity/title (Required)",
    required: true,
    type: "string",
    aliases: [
      "product name",
      "product",
      "name",
      "item name",
      "item",
      "item description",
      "product description",
      "product title",
      "title",
      "product_name",
      "item_name",
      "description",
      "desc",
      "particulars",
      "item particulars",
      "articulo",
      "nom",
      "goods name",
      "goods",
      "medicine name",
      "drug name",
      "medicine",
      "trade name",
      "generic name",
      "brand name",
      "dawa",
      "naam",
      "product title / name",
      "items list",
      "product_desc",
    ],
  },
  {
    key: "internal_sku",
    label: "SKU / Item Code",
    description: "Internal inventory SKU or product code",
    required: false,
    type: "string",
    aliases: [
      "sku",
      "internal sku",
      "item code",
      "product code",
      "item no",
      "item number",
      "product id",
      "item id",
      "product no",
      "internal code",
      "code",
      "item_code",
      "product_code",
      "ref",
      "reference",
      "model",
      "part number",
      "part no",
      "catalog no",
      "sku code",
      "sku_number",
      "item_id",
      "prod_code",
    ],
  },
  {
    key: "purchase_cost",
    label: "Purchase Price",
    description: "Buying cost / purchase rate per unit",
    required: false,
    type: "number",
    aliases: [
      "cost",
      "cost price",
      "purchase price",
      "buying price",
      "buy rate",
      "purchase rate",
      "buying rate",
      "unit cost",
      "cp",
      "cost_price",
      "purchase_cost",
      "pur rate",
      "pur price",
      "cost per unit",
      "supplier price",
      "wholesale price",
      "trade price",
      "tp",
      "net rate",
      "purchase",
      "pur_rate",
      "pur_price",
      "buy_price",
    ],
  },
  {
    key: "retail_price",
    label: "Retail Price",
    description: "Selling price / MRP per unit",
    required: false,
    type: "number",
    aliases: [
      "selling price",
      "sale price",
      "retail",
      "retail price",
      "mrp",
      "price",
      "rate",
      "sale rate",
      "selling rate",
      "unit price",
      "sp",
      "retail_price",
      "selling_price",
      "list price",
      "sales price",
      "consumer price",
      "customer price",
      "m.r.p",
      "m.r.p.",
      "retail rate",
      "rate / unit",
      "price / unit",
      "sell rate",
    ],
  },
  {
    key: "discount_price",
    label: "Discount",
    description: "Discounted sale price or discount percentage",
    required: false,
    type: "number",
    aliases: [
      "discount",
      "discount price",
      "promo price",
      "offer price",
      "sale discount",
      "cut price",
      "disc",
      "discount_price",
      "discount %",
      "discount rate",
      "disc %",
      "special price",
      "deal price",
    ],
  },
  {
    key: "stock_units",
    label: "Stock Units",
    description: "Available quantity in inventory",
    required: false,
    type: "number",
    aliases: [
      "qty",
      "quantity",
      "stock",
      "stock units",
      "available",
      "available qty",
      "current stock",
      "on hand",
      "units",
      "balance qty",
      "in stock",
      "count",
      "quantity on hand",
      "physical stock",
      "stock_units",
      "stock_qty",
      "bal qty",
      "closing stock",
      "net stock",
      "pieces",
      "nos",
      "total units",
      "qnty",
    ],
  },
  {
    key: "min_stock_alert",
    label: "Min Stock Alert",
    description: "Low-stock warning threshold",
    required: false,
    type: "number",
    aliases: [
      "min stock",
      "min stock alert",
      "reorder level",
      "low stock threshold",
      "safety stock",
      "min qty",
      "minimum quantity",
      "alert level",
      "min_stock",
      "reorder point",
      "min_stock_alert",
      "reorder_qty",
      "threshold",
    ],
  },
  {
    key: "category",
    label: "Primary Category",
    description: "Product category (Validated against catalog)",
    required: false,
    type: "string",
    aliases: [
      "category",
      "department",
      "dept",
      "group",
      "product group",
      "main category",
      "cat",
      "category name",
      "section",
      "family",
      "classification",
      "parent category",
      "product_type",
      "type",
      "item_group",
    ],
  },
  {
    key: "subcategory",
    label: "Subcategory",
    description: "Secondary subcategory under primary category",
    required: false,
    type: "string",
    aliases: [
      "subcategory",
      "sub category",
      "sub group",
      "sub department",
      "sub_category",
      "sub-category",
      "subcat",
      "child category",
      "sub_group",
      "segment",
    ],
  },
  {
    key: "uom",
    label: "Unit of Measure (UOM)",
    description: "Base counting unit (e.g. piece, box, bottle, strip)",
    required: false,
    type: "string",
    aliases: [
      "uom",
      "unit of measure",
      "unit",
      "base unit",
      "stock unit",
      "measure",
      "measurement unit",
      "stock_unit",
      "unit_of_measure",
      "uom_name",
      "packing unit",
      "units_uom",
    ],
  },
  {
    key: "packaging",
    label: "Packaging Type",
    description: "Physical packaging (e.g. Box, Bottle, Blister, Carton)",
    required: false,
    type: "string",
    aliases: [
      "packaging",
      "package type",
      "pack type",
      "packing",
      "container",
      "packaging_type",
      "pack_type",
      "container type",
      "package",
    ],
  },
  {
    key: "pack_size",
    label: "Pack Size",
    description: "Units per package (e.g. 10 tablets/strip, 24 cans/case)",
    required: false,
    type: "number",
    aliases: [
      "pack size",
      "units per pack",
      "case quantity",
      "box quantity",
      "packing size",
      "items per pack",
      "pack_size",
      "units_per_package",
      "pieces per box",
      "units_per_box",
    ],
  },
  {
    key: "strength",
    label: "Strength / Formulation",
    description: "Active ingredient dosage or specification (e.g. 500mg)",
    required: false,
    type: "string",
    aliases: [
      "strength",
      "dosage",
      "formulation",
      "power",
      "potency",
      "dose",
      "specification",
      "spec",
      "mg",
      "size/strength",
    ],
  },
  {
    key: "brand",
    label: "Brand / Manufacturer",
    description: "Brand name, manufacturer or company",
    required: false,
    type: "string",
    aliases: [
      "brand",
      "manufacturer",
      "company",
      "mfg",
      "producer",
      "make",
      "vendor",
      "supplier name",
      "mfg by",
      "brand name",
      "mfg_company",
    ],
  },
  {
    key: "barcode",
    label: "Barcode / UPC / EAN",
    description: "Scannable barcode or GTIN",
    required: false,
    type: "string",
    aliases: [
      "barcode",
      "upc",
      "ean",
      "gtin",
      "bar code",
      "upc code",
      "ean13",
      "ean-13",
      "barcode_number",
      "scan code",
      "isbn",
      "serial",
    ],
  },
  {
    key: "batch_number",
    label: "Batch / Lot Number",
    description: "Manufacturing batch or lot code",
    required: false,
    type: "string",
    aliases: [
      "batch",
      "batch number",
      "lot",
      "lot number",
      "batch no",
      "lot no",
      "b.no",
      "batch_no",
      "lot_no",
      "batch_number",
      "lot_number",
      "b_no",
    ],
  },
  {
    key: "expiry_date",
    label: "Expiry Date",
    description: "Product expiration date (YYYY-MM-DD)",
    required: false,
    type: "date",
    aliases: [
      "expiry",
      "expiry date",
      "expiration",
      "exp date",
      "best before",
      "valid till",
      "exp",
      "exp_date",
      "expiry_date",
      "expiration_date",
      "validity",
    ],
  },
  {
    key: "images",
    label: "Product Image URL(s)",
    description: "Image URLs separated by commas",
    required: false,
    type: "string",
    aliases: [
      "image",
      "images",
      "image url",
      "photo",
      "picture",
      "image link",
      "image_urls",
      "photo_url",
    ],
  },
  {
    key: "status",
    label: "Status",
    description: "active, draft, or archived",
    required: false,
    type: "string",
    aliases: ["status", "state", "product status", "item status"],
  },
  {
    key: "metadata",
    label: "Custom Metadata (JSON)",
    description: "Stored in product metadata JSON",
    required: false,
    type: "string",
    aliases: ["notes", "remarks", "extra", "custom", "metadata", "comment"],
  },
  {
    key: "ignore",
    label: "Do Not Import (Ignore)",
    description: "Skip this column during import",
    required: false,
    type: "string",
    aliases: ["ignore", "skip", "none", "unused", "na"],
  },
];
