import { useState, useMemo } from "react";
import { EMAIL_TEMPLATES, EmailTemplate } from "@/lib/emailTemplates";
import { getAppUrl, getRecommendedSupabaseRedirectUrls } from "@/lib/appUrl";
import { usePlatformSettings } from "@/components/PlatformSettingsProvider";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  Check,
  Code2,
  Copy,
  ExternalLink,
  Eye,
  Globe,
  Info,
  Link as LinkIcon,
  Mail,
  RotateCcw,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Monitor,
  Sliders,
  Palette,
  Layers,
  Type,
  Maximize2,
  Save,
  CheckCircle2,
  FileText,
  Undo2,
  Pencil,
  Image as ImageIcon,
  MousePointerClick,
  Settings2,
  HelpCircle,
  KeyRound,
  ArrowRight,
} from "lucide-react";

export interface TemplateCustomFields {
  subject: string;
  brandName: string;
  brandAccent: string;
  logoUrl?: string;
  useCustomLogo?: boolean;
  logoHeight?: number;
  badgeText: string;
  badgeColor: string;
  title: string;
  description: string;
  ctaText: string;
  ctaLink: string;
  ctaBgColor: string;
  ctaTextColor: string;
  ctaBorderRadius?: string; // '8px' | '12px' | '16px' | '9999px'
  footerSiteUrl: string;
  footerSupportEmail: string;
  footerText: string;
  securityNote: string;
  rawHtml?: string;
  useRawHtml?: boolean;
}

interface UrlPreset {
  label: string;
  url: string;
  description: string;
  badge?: string;
}

const TEMPLATE_URL_PRESETS: Record<string, UrlPreset[]> = {
  reset_password: [
    {
      label: "Supabase Direct Recovery URL",
      url: "{{ .ConfirmationURL }}",
      description: "Default secure Supabase token link that auto-verifies and redirects to your set new password page (/reset-password).",
      badge: "Recommended",
    },
    {
      label: "Direct Set New Password Route",
      url: "{{ .SiteURL }}/reset-password",
      description: "Sends the user directly to the new password creation page.",
    },
    {
      label: "Password Reset with Token Hash",
      url: "{{ .SiteURL }}/reset-password?token_hash={{ .TokenHash }}&type=recovery",
      description: "Appends the secure token_hash to the /reset-password URL for client-side OTP validation.",
    },
    {
      label: "Auth Callback Recovery Relay",
      url: "{{ .SiteURL }}/auth/callback?type=recovery&next=/reset-password",
      description: "Passes through the Auth Callback handler before routing to password reset.",
    },
  ],
  magic_link: [
    {
      label: "Supabase Magic Link Action",
      url: "{{ .ConfirmationURL }}",
      description: "One-click passwordless login link generated by Supabase with one-time verification token.",
      badge: "Recommended",
    },
    {
      label: "Internal Auth Callback Handler",
      url: "{{ .SiteURL }}/auth/callback?type=magiclink",
      description: "Relays OTP code through your application callback route.",
    },
    {
      label: "Direct Workspace Dashboard",
      url: "{{ .SiteURL }}/dashboard",
      description: "Direct link to workspace dashboard.",
    },
  ],
  signup_confirmation: [
    {
      label: "Supabase Email Verification Link",
      url: "{{ .ConfirmationURL }}",
      description: "Direct confirmation link that activates the new account in Supabase Auth.",
      badge: "Recommended",
    },
    {
      label: "Verify & Launch Business Setup Wizard",
      url: "{{ .SiteURL }}/auth/callback?type=signup&next=/setup/business",
      description: "Verifies email and directs user immediately into the business setup onboarding.",
    },
    {
      label: "Direct Business Setup Route",
      url: "{{ .SiteURL }}/setup/business",
      description: "Routes verified user straight to workspace initialization.",
    },
  ],
  change_email: [
    {
      label: "Confirm Email Change Link",
      url: "{{ .ConfirmationURL }}",
      description: "Supabase verification link to activate new user email address.",
      badge: "Recommended",
    },
    {
      label: "Email Change Callback Relay",
      url: "{{ .SiteURL }}/auth/callback?type=email_change",
      description: "Callback endpoint for processing email change confirmation.",
    },
  ],
  invite_user: [
    {
      label: "Supabase Team Invite Token Link",
      url: "{{ .ConfirmationURL }}",
      description: "One-time invitation token linking user to the workspace.",
      badge: "Recommended",
    },
    {
      label: "Accept Invite & Launch Dashboard",
      url: "{{ .SiteURL }}/auth/callback?type=invite&next=/dashboard",
      description: "Confirms invitation and loads team workspace.",
    },
  ],
};

const SHORTCODE_TAGS = [
  { tag: "{{ .ConfirmationURL }}", label: "Confirmation URL", desc: "Full dynamic one-time authentication link generated by Supabase" },
  { tag: "{{ .SiteURL }}", label: "Site URL", desc: "Main project domain (e.g. geflowai.com or current dev host)" },
  { tag: "{{ .Token }}", label: "6-Digit Code", desc: "One-time security OTP token / code" },
  { tag: "{{ .TokenHash }}", label: "Token Hash", desc: "Hashed security token for custom URL verification" },
  { tag: "{{ .Email }}", label: "User Email", desc: "Recipient user email address" },
];

const STORAGE_KEY = "geflow_admin_email_templates_custom_v5";

const DEFAULT_CONFIGS: Record<string, TemplateCustomFields> = {
  magic_link: {
    subject: "Your GeFlow One-Time Login Link & Code: {{ .Token }}",
    brandName: "GeFlow",
    brandAccent: "#38bdf8",
    useCustomLogo: false,
    logoHeight: 36,
    badgeText: "Passwordless Authentication",
    badgeColor: "#38bdf8",
    title: "Your One-Time Login Link",
    description:
      "Click the button below or use your 6-digit code to securely sign in to your GeFlow account without entering a password.",
    ctaText: "👉 Instant Log In to GeFlow",
    ctaLink: "{{ .ConfirmationURL }}",
    ctaBgColor: "#38bdf8",
    ctaTextColor: "#041017",
    ctaBorderRadius: "12px",
    footerSiteUrl: "{{ .SiteURL }}",
    footerSupportEmail: "support@geflowai.com",
    footerText: "GeFlow Business Cloud Management Platform",
    securityNote:
      "This link and code will expire in 10 minutes. If you did not request this email, you can safely ignore it.",
    useRawHtml: false,
  },
  signup_confirmation: {
    subject: "Welcome to GeFlow — Confirm Your Account",
    brandName: "GeFlow",
    brandAccent: "#38bdf8",
    useCustomLogo: false,
    logoHeight: 36,
    badgeText: "Welcome Onboard",
    badgeColor: "#10b981",
    title: "Confirm Your Email Address",
    description:
      "Thank you for joining GeFlow. Please click the button below to verify your email address and activate your business workspace.",
    ctaText: "✓ Verify Email & Activate Account",
    ctaLink: "{{ .ConfirmationURL }}",
    ctaBgColor: "#38bdf8",
    ctaTextColor: "#041017",
    ctaBorderRadius: "12px",
    footerSiteUrl: "{{ .SiteURL }}",
    footerSupportEmail: "support@geflowai.com",
    footerText: "GeFlow POS & Inventory Management",
    securityNote:
      "This verification link will expire in 24 hours. After verifying, you will be guided through your workspace onboarding.",
    useRawHtml: false,
  },
  reset_password: {
    subject: "Reset Your GeFlow Password",
    brandName: "GeFlow",
    brandAccent: "#38bdf8",
    useCustomLogo: false,
    logoHeight: 36,
    badgeText: "Security Notice",
    badgeColor: "#f43f5e",
    title: "Reset Your Password",
    description:
      "We received a request to reset the password for your GeFlow account. Click the button below to set a new password:",
    ctaText: "🔒 Reset Password & Set New Credentials",
    ctaLink: "{{ .ConfirmationURL }}",
    ctaBgColor: "#f43f5e",
    ctaTextColor: "#ffffff",
    ctaBorderRadius: "12px",
    footerSiteUrl: "{{ .SiteURL }}",
    footerSupportEmail: "security@geflowai.com",
    footerText: "GeFlow Security & Access Control",
    securityNote:
      "If you did not request a password reset, you can safely ignore this email. Your password will remain unchanged.",
    useRawHtml: false,
  },
  change_email: {
    subject: "Confirm Your New Email Address for GeFlow",
    brandName: "GeFlow",
    brandAccent: "#38bdf8",
    useCustomLogo: false,
    logoHeight: 36,
    badgeText: "Account Update",
    badgeColor: "#38bdf8",
    title: "Confirm New Email Address",
    description:
      "A request was made to update your GeFlow account email to this address. Click the button below to confirm and activate this change:",
    ctaText: "✓ Confirm Email Change",
    ctaLink: "{{ .ConfirmationURL }}",
    ctaBgColor: "#38bdf8",
    ctaTextColor: "#041017",
    ctaBorderRadius: "12px",
    footerSiteUrl: "{{ .SiteURL }}",
    footerSupportEmail: "support@geflowai.com",
    footerText: "GeFlow Security • Access Protection",
    securityNote:
      "If you did not request this update, please contact our security team immediately at security@geflowai.com.",
    useRawHtml: false,
  },
  invite_user: {
    subject: "You've been invited to join a GeFlow Workspace",
    brandName: "GeFlow",
    brandAccent: "#38bdf8",
    useCustomLogo: false,
    logoHeight: 36,
    badgeText: "Team Invitation",
    badgeColor: "#8b5cf6",
    title: "You're Invited!",
    description:
      "You have been invited to collaborate on a GeFlow business workspace. Click below to accept the invitation and set up your team profile:",
    ctaText: "🤝 Accept Team Invitation",
    ctaLink: "{{ .ConfirmationURL }}",
    ctaBgColor: "#8b5cf6",
    ctaTextColor: "#ffffff",
    ctaBorderRadius: "12px",
    footerSiteUrl: "{{ .SiteURL }}",
    footerSupportEmail: "support@geflowai.com",
    footerText: "GeFlow Team Collaboration",
    securityNote:
      "This invitation link is valid for 7 days. If you do not recognize this business, you may safely disregard this email.",
    useRawHtml: false,
  },
};

/**
 * Builds responsive, email-client-compatible HTML with full Elementor-style visual customization
 */
function buildHtmlFromFields(
  id: string,
  fields: TemplateCustomFields,
  defaultProjectLogoUrl?: string | null
): string {
  const isMagicLink = id === "magic_link";
  const activeLogoUrl = fields.useCustomLogo
    ? fields.logoUrl?.trim()
    : defaultProjectLogoUrl || fields.logoUrl?.trim();

  const logoMarkup = activeLogoUrl
    ? `<img src="${activeLogoUrl}" alt="${fields.brandName || "GeFlow"}" style="max-height: ${fields.logoHeight || 36}px; max-width: 180px; height: auto; display: inline-block; object-fit: contain;" />`
    : `<span style="font-size: 26px; font-weight: 800; letter-spacing: -0.5px; color: #ffffff; text-decoration: none; display: inline-block;">${fields.brandName || "GeFlow"}</span>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${fields.title}</title>
  <style>
    body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0c0f17; color: #f1f5f9; }
    .container { max-width: 580px; margin: 40px auto; background: #131825; border: 1px solid #1e293b; border-radius: 24px; overflow: hidden; box-shadow: 0 20px 40px rgba(0,0,0,0.5); }
    .header { padding: 36px 40px 24px; text-align: center; border-bottom: 1px solid rgba(255,255,255,0.06); background: linear-gradient(180deg, rgba(56,189,248,0.08) 0%, rgba(19,24,37,0) 100%); }
    .badge { display: inline-block; padding: 6px 14px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: ${fields.badgeColor || "#38bdf8"}; background: rgba(56,189,248,0.12); border: 1px solid ${fields.badgeColor || "#38bdf8"}40; border-radius: 100px; margin-top: 12px; }
    .content { padding: 36px 40px; text-align: center; }
    .title { font-size: 24px; font-weight: 700; color: #ffffff; margin: 0 0 12px; }
    .desc { font-size: 15px; line-height: 1.6; color: #94a3b8; margin: 0 0 28px; }
    .code-box { background: #0b0e14; border: 1px dashed ${fields.brandAccent || "#38bdf8"}; border-radius: 16px; padding: 18px 24px; margin: 0 auto 28px; display: inline-block; min-width: 240px; }
    .code-label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; color: #64748b; margin-bottom: 6px; }
    .code-value { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; font-size: 32px; font-weight: 800; letter-spacing: 6px; color: ${fields.brandAccent || "#38bdf8"}; }
    .btn { display: inline-block; background: ${fields.ctaBgColor || "#38bdf8"}; color: ${fields.ctaTextColor || "#041017"} !important; font-size: 15px; font-weight: 700; text-decoration: none; padding: 14px 36px; border-radius: ${fields.ctaBorderRadius || "12px"}; box-shadow: 0 10px 20px rgba(0,0,0,0.3); }
    .divider { height: 1px; background: #1e293b; margin: 32px 0 24px; }
    .footer { padding: 0 40px 36px; text-align: center; font-size: 12px; color: #64748b; line-height: 1.5; }
    .footer a { color: #94a3b8; text-decoration: underline; }
    .security-note { font-size: 12px; color: #64748b; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>${logoMarkup}</div>
      ${fields.badgeText ? `<div><span class="badge">${fields.badgeText}</span></div>` : ""}
    </div>
    
    <div class="content">
      <h1 class="title">${fields.title}</h1>
      <p class="desc">${fields.description}</p>

      ${
        isMagicLink
          ? `<!-- 6-digit OTP Code Box -->
      <div class="code-box">
        <div class="code-label">One-Time Security Code</div>
        <div class="code-value">{{ .Token }}</div>
      </div>`
          : ""
      }

      <div>
        <a href="${fields.ctaLink || "{{ .ConfirmationURL }}"}" class="btn" target="_blank">
          ${fields.ctaText}
        </a>
      </div>

      ${
        fields.securityNote
          ? `<p class="security-note">${fields.securityNote}</p>`
          : ""
      }

      <div class="divider"></div>

      <p style="font-size: 12px; color: #64748b; margin: 0;">
        Trouble clicking the button? Copy and paste this URL into your browser:<br>
        <span style="color: ${fields.brandAccent || "#38bdf8"}; word-break: break-all;">${fields.ctaLink || "{{ .ConfirmationURL }}"}</span>
      </p>
    </div>

    <div class="footer">
      <p style="margin: 0 0 6px;">${fields.footerText || "GeFlow Business Management Platform"}</p>
      <p style="margin: 0;">
        Support: <a href="mailto:${fields.footerSupportEmail || "support@geflowai.com"}">${fields.footerSupportEmail || "support@geflowai.com"}</a> &bull; <a href="${fields.footerSiteUrl || "{{ .SiteURL }}"}">Visit Workspace</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

export const EmailTemplatesManager = () => {
  const { toast } = useToast();
  const { settings } = usePlatformSettings();
  const [selectedId, setSelectedId] = useState<string>("magic_link");
  const [isEditorPopupOpen, setIsEditorPopupOpen] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<"content" | "cta" | "branding" | "footer" | "code">("cta");
  const [deviceMode, setDeviceMode] = useState<"desktop" | "mobile">("desktop");
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const activeAppUrl = getAppUrl();
  const recommendedRedirects = getRecommendedSupabaseRedirectUrls();

  // Load custom template configs from LocalStorage or fallback to default
  const [templateConfigs, setTemplateConfigs] = useState<Record<string, TemplateCustomFields>>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        return { ...DEFAULT_CONFIGS, ...parsed };
      }
    } catch (e) {
      console.warn("Failed to parse custom email templates", e);
    }
    return DEFAULT_CONFIGS;
  });

  const currentTpl = EMAIL_TEMPLATES.find((t) => t.id === selectedId) || EMAIL_TEMPLATES[0];
  const currentConfig = templateConfigs[selectedId] || DEFAULT_CONFIGS[selectedId] || DEFAULT_CONFIGS.magic_link;
  const currentPresets = TEMPLATE_URL_PRESETS[selectedId] || TEMPLATE_URL_PRESETS.reset_password;

  // Real-time update handler with instant LocalStorage caching
  const updateField = (field: keyof TemplateCustomFields, value: any) => {
    setTemplateConfigs((prev) => {
      const updated = {
        ...prev,
        [selectedId]: {
          ...(prev[selectedId] || DEFAULT_CONFIGS[selectedId]),
          [field]: value,
        },
      };
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      } catch (e) {
        // ignore
      }
      return updated;
    });
  };

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(label);
    toast({
      title: `${label} Copied! 📋`,
      description: "Copied to your clipboard. Paste into your Supabase Dashboard.",
    });
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleCopyAllRedirects = () => {
    const text = recommendedRedirects.join("\n");
    handleCopy(text, "All Redirect URLs");
  };

  const handleResetCurrentTemplate = () => {
    const defaults = DEFAULT_CONFIGS[selectedId];
    if (defaults) {
      setTemplateConfigs((prev) => {
        const updated = { ...prev, [selectedId]: { ...defaults } };
        localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
        return updated;
      });
      toast({
        title: "Template Reset",
        description: "Reverted current template to clean default configuration.",
      });
    }
  };

  // Compile final HTML string (either visual builder output or custom raw HTML)
  const finalHtml = useMemo(() => {
    if (currentConfig.useRawHtml && currentConfig.rawHtml) {
      return currentConfig.rawHtml;
    }
    return buildHtmlFromFields(selectedId, currentConfig, settings?.logo_url);
  }, [selectedId, currentConfig, settings?.logo_url]);

  // Live preview replacing Go Template dynamic tokens
  const renderedPreviewHtml = useMemo(() => {
    return finalHtml
      .replace(/\{\{\s*\.Token\s*\}\}/g, "849201")
      .replace(
        /\{\{\s*\.ConfirmationURL\s*\}\}/g,
        `${activeAppUrl}/reset-password?token_hash=sample_token_849201&type=recovery`
      )
      .replace(/\{\{\s*\.TokenHash\s*\}\}/g, "sample_token_hash_849201")
      .replace(/\{\{\s*\.SiteURL\s*\}\}/g, activeAppUrl)
      .replace(/\{\{\s*\.Email\s*\}\}/g, "customer@geflowai.com");
  }, [finalHtml, activeAppUrl]);

  return (
    <div className="space-y-6">
      {/* Top Banner & Status */}
      <div className="p-5 rounded-2xl border border-sky-500/20 bg-sky-500/5 dark:bg-sky-500/10 flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
        <div className="flex items-start gap-3.5">
          <div className="h-11 w-11 rounded-2xl bg-sky-500/20 text-sky-500 flex items-center justify-center flex-shrink-0 mt-0.5 shadow-sm">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="font-bold text-sm text-foreground">
                Email Templates, CTA URL Router & Shortcode Editor
              </h3>
              <Badge variant="outline" className="text-sky-500 border-sky-500/30 text-[10px] py-0 font-mono">
                Domain: geflowai.com
              </Badge>
              <Badge variant="secondary" className="text-emerald-500 bg-emerald-500/10 text-[10px] py-0 font-medium">
                Live Supabase Sync
              </Badge>
            </div>
            <p className="text-xs text-muted-foreground mt-1 max-w-3xl leading-relaxed">
              Canonical Application URL: <code className="px-1.5 py-0.5 rounded bg-muted font-mono text-foreground font-semibold">{activeAppUrl}</code>.
              Admins can customize CTA button URLs (custom link, set new password page link, or Supabase variable tags like <code className="font-mono text-sky-500">{"{{ .ConfirmationURL }}"}</code>), button text, coloration, and logo in seconds with instant live preview.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-shrink-0 flex-wrap">
          <Button
            size="sm"
            variant="outline"
            onClick={handleCopyAllRedirects}
            className="h-9 rounded-xl text-xs gap-1.5 font-semibold"
          >
            {copiedField === "All Redirect URLs" ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
            Copy Supabase Redirects
          </Button>

          <a
            href="https://supabase.com/dashboard/project/bglzohtmgamypgooddru/auth/url-configuration"
            target="_blank"
            rel="noopener noreferrer"
            className="px-3.5 py-2 rounded-xl bg-sky-500 hover:bg-sky-600 text-white font-semibold text-xs inline-flex items-center gap-1.5 transition-colors shadow-sm"
          >
            Supabase Config <ExternalLink className="h-3.5 w-3.5" />
          </a>
        </div>
      </div>

      {/* Main Grid: Left Template Selector & Right Top-Aligned Live Preview */}
      <div className="grid lg:grid-cols-12 gap-6 items-start">
        {/* Left Column: Template Cards & Actions */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-card border border-border rounded-2xl p-5 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                Authentication Email Templates
              </label>
              <span className="text-[11px] text-muted-foreground font-medium">
                {EMAIL_TEMPLATES.length} Auth Flow Templates
              </span>
            </div>

            <div className="grid grid-cols-1 gap-2.5">
              {EMAIL_TEMPLATES.map((t) => {
                const isSelected = t.id === selectedId;
                const config = templateConfigs[t.id] || DEFAULT_CONFIGS[t.id];

                return (
                  <div
                    key={t.id}
                    className={`group relative p-4 rounded-xl border transition-all cursor-pointer ${
                      isSelected
                        ? "border-sky-500 bg-sky-500/10 dark:bg-sky-500/15 shadow-sm"
                        : "border-border hover:border-border/80 hover:bg-muted/40"
                    }`}
                    onClick={() => setSelectedId(t.id)}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <div className="flex items-center gap-2">
                          <span
                            className={`text-sm font-bold ${
                              isSelected ? "text-sky-500 dark:text-sky-400" : "text-foreground"
                            }`}
                          >
                            {t.name}
                          </span>
                          <Badge variant="secondary" className="text-[10px] capitalize">
                            {t.category}
                          </Badge>
                        </div>
                        <p className="text-xs text-muted-foreground mt-1 line-clamp-2 leading-relaxed">
                          {config?.title || t.description}
                        </p>
                      </div>

                      <div className="flex-shrink-0 flex items-center gap-1">
                        <Button
                          size="sm"
                          variant={isSelected ? "default" : "secondary"}
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedId(t.id);
                            setIsEditorPopupOpen(true);
                          }}
                          className={`h-8 px-3 rounded-lg text-xs font-semibold gap-1.5 shadow-xs transition-transform ${
                            isSelected
                              ? "bg-sky-500 hover:bg-sky-600 text-white"
                              : "opacity-90 group-hover:opacity-100 group-hover:scale-105"
                          }`}
                        >
                          <Pencil className="h-3 w-3" />
                          Edit Template
                        </Button>
                      </div>
                    </div>

                    {/* Quick overview pill list */}
                    <div className="mt-3 pt-2.5 border-t border-border/50 flex flex-col gap-1.5 text-[11px] text-muted-foreground">
                      <div className="flex items-center justify-between flex-wrap gap-1">
                        <span className="flex items-center gap-1 truncate max-w-[260px]">
                          <LinkIcon className="h-3 w-3 text-sky-500" /> CTA: <strong className="text-foreground">{config?.ctaText}</strong>
                        </span>
                        <Badge variant="outline" className="font-mono text-[9px] text-sky-500 py-0 border-sky-500/30">
                          {config?.ctaLink || "{{ .ConfirmationURL }}"}
                        </Badge>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* User Reset Password Flow & Security Logic Explanation Box */}
          <div className="bg-card border border-border rounded-2xl p-5 space-y-3.5 shadow-xs">
            <div className="flex items-center gap-2">
              <KeyRound className="h-4 w-4 text-amber-500" />
              <h4 className="font-bold text-xs uppercase tracking-wider text-foreground">
                Password Reset & Security Lifecycle
              </h4>
            </div>

            <div className="text-xs text-muted-foreground space-y-2.5 leading-relaxed">
              <div className="p-3 rounded-xl bg-muted/40 border border-border/60 space-y-1.5">
                <p className="font-semibold text-foreground flex items-center gap-1.5">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> 1. Request & Email Dispatch
                </p>
                <p>
                  When a user clicks "Forgot Password", Supabase generates a single-use cryptographically signed recovery token and dispatches the recovery email.
                </p>
              </div>

              <div className="p-3 rounded-xl bg-muted/40 border border-border/60 space-y-1.5">
                <p className="font-semibold text-foreground flex items-center gap-1.5">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> 2. CTA Click ➔ Set New Password Page
                </p>
                <p>
                  Clicking the CTA button verifies the token and routes the user to <code className="font-mono text-foreground font-semibold">/reset-password</code> where they specify their new password.
                </p>
              </div>

              <div className="p-3 rounded-xl bg-muted/40 border border-border/60 space-y-1.5">
                <p className="font-semibold text-foreground flex items-center gap-1.5">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" /> 3. Old Password Invalidation in Supabase
                </p>
                <p>
                  Upon submission, Supabase securely re-hashes the new password, removes and invalidates the previous password credentials immediately, and prevents old password logins across all devices.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Clean Top-Aligned Live Preview */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-card border border-border rounded-2xl p-5 shadow-xs flex flex-col">
            {/* Clean Preview Header */}
            <div className="flex items-center justify-between pb-4 border-b border-border flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <div className="h-2.5 w-2.5 rounded-full bg-emerald-500 animate-pulse" />
                <span className="font-bold text-sm text-foreground">
                  {currentTpl.name} Preview
                </span>
                <Badge variant="outline" className="text-[10px] text-muted-foreground">
                  Top-Aligned
                </Badge>
              </div>

              <div className="flex items-center gap-2">
                {/* Desktop vs Mobile switcher */}
                <div className="inline-flex rounded-lg border border-border p-0.5 bg-muted/40">
                  <button
                    type="button"
                    onClick={() => setDeviceMode("desktop")}
                    className={`p-1.5 px-2 rounded-md text-xs font-semibold flex items-center gap-1 transition-colors ${
                      deviceMode === "desktop" ? "bg-background text-foreground shadow-xs" : "text-muted-foreground"
                    }`}
                  >
                    <Monitor className="h-3.5 w-3.5" /> Desktop
                  </button>
                  <button
                    type="button"
                    onClick={() => setDeviceMode("mobile")}
                    className={`p-1.5 px-2 rounded-md text-xs font-semibold flex items-center gap-1 transition-colors ${
                      deviceMode === "mobile" ? "bg-background text-foreground shadow-xs" : "text-muted-foreground"
                    }`}
                  >
                    <Smartphone className="h-3.5 w-3.5" /> Mobile
                  </button>
                </div>

                {/* Open Full Customizer Modal Button */}
                <Button
                  onClick={() => setIsEditorPopupOpen(true)}
                  className="h-8 rounded-lg bg-sky-500 hover:bg-sky-600 text-white font-semibold text-xs gap-1.5 shadow-xs"
                >
                  <Sliders className="h-3.5 w-3.5" /> Customize in Visual Popup
                </Button>
              </div>
            </div>

            {/* Live Render Canvas - Strictly Top Aligned */}
            <div className="mt-4 flex flex-col items-center justify-start bg-muted/20 dark:bg-black/40 rounded-xl p-4 border border-border/50 min-h-[600px] overflow-auto">
              <div
                className={`transition-all duration-300 w-full overflow-hidden shadow-xl rounded-2xl border border-border bg-[#0c0f17] ${
                  deviceMode === "mobile" ? "max-w-[380px]" : "max-w-[620px]"
                }`}
              >
                {/* Mockup Mail Header */}
                <div className="bg-[#131825] px-4 py-2.5 border-b border-[#1e293b] flex items-center justify-between text-[11px] text-slate-400">
                  <div className="truncate font-semibold max-w-[75%]">
                    <span className="text-slate-500">Subject:</span>{" "}
                    {currentConfig.subject.replace("{{ .Token }}", "849201")}
                  </div>
                  <span className="text-emerald-400 font-mono text-[10px] bg-emerald-500/10 px-2 py-0.5 rounded-full flex-shrink-0">
                    Live HTML
                  </span>
                </div>

                <iframe
                  title="Email Live Preview"
                  srcDoc={renderedPreviewHtml}
                  className="w-full h-[580px] border-none bg-[#0c0f17] block"
                />
              </div>

              {/* Action Bar Under Preview */}
              <div className="w-full max-w-[620px] mt-4 flex items-center justify-between flex-wrap gap-2 pt-2 border-t border-border/40">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleCopy(finalHtml, "Compiled Supabase HTML")}
                  className="h-9 rounded-xl text-xs gap-1.5 font-semibold"
                >
                  {copiedField === "Compiled Supabase HTML" ? (
                    <Check className="h-3.5 w-3.5 text-emerald-500" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                  Copy Generated Supabase HTML
                </Button>

                <Button
                  size="sm"
                  onClick={() => setIsEditorPopupOpen(true)}
                  className="h-9 rounded-xl bg-sky-500 hover:bg-sky-600 text-white font-bold text-xs gap-1.5"
                >
                  <Pencil className="h-3.5 w-3.5" /> Edit Template Fields
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* FULL ELEMENTOR-STYLE VISUAL CUSTOMIZER POPUP DIALOG                       */}
      {/* ========================================================================= */}
      <Dialog open={isEditorPopupOpen} onOpenChange={setIsEditorPopupOpen}>
        <DialogContent className="max-w-6xl w-[96vw] h-[92vh] max-h-[92vh] p-0 overflow-hidden flex flex-col rounded-2xl border-border bg-card shadow-2xl">
          {/* Modal Header */}
          <div className="px-6 py-4 border-b border-border flex items-center justify-between bg-muted/20 flex-shrink-0">
            <div className="flex items-center gap-3">
              <div className="h-9 w-9 rounded-xl bg-sky-500/10 text-sky-500 flex items-center justify-center font-bold">
                <Sliders className="h-4 w-4" />
              </div>
              <div>
                <DialogTitle className="text-base font-bold text-foreground flex items-center gap-2">
                  Visual Email Customizer — {currentTpl.name}
                  <Badge variant="outline" className="text-sky-500 border-sky-500/30 text-[10px]">
                    Elementor-Style
                  </Badge>
                </DialogTitle>
                <DialogDescription className="text-xs text-muted-foreground">
                  Customize CTA action URLs, preset destination links, shortcodes, button styling, and brand assets.
                </DialogDescription>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleResetCurrentTemplate}
                className="h-8 text-xs text-muted-foreground hover:text-foreground gap-1"
              >
                <RotateCcw className="h-3 w-3" /> Reset Defaults
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  handleCopy(finalHtml, "Compiled HTML");
                  setIsEditorPopupOpen(false);
                }}
                className="h-8 rounded-lg bg-sky-500 hover:bg-sky-600 text-white font-bold text-xs gap-1.5 shadow-sm"
              >
                <Check className="h-3.5 w-3.5" /> Save & Copy HTML
              </Button>
            </div>
          </div>

          {/* Modal Body: Split 2-Column Visual Builder */}
          <div className="grid lg:grid-cols-12 flex-1 overflow-hidden">
            {/* Left Column: Form Controls with Section Tabs */}
            <div className="lg:col-span-6 border-r border-border flex flex-col h-full overflow-hidden bg-background">
              {/* Tabs Switcher */}
              <div className="flex items-center gap-1 p-2 border-b border-border bg-muted/30 overflow-x-auto">
                <button
                  type="button"
                  onClick={() => setActiveTab("cta")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                    activeTab === "cta" ? "bg-background text-foreground shadow-xs border" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <MousePointerClick className="h-3.5 w-3.5 text-sky-500" /> CTA & URL Router
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("content")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                    activeTab === "content" ? "bg-background text-foreground shadow-xs border" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Type className="h-3.5 w-3.5 text-sky-500" /> Content & Text
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("branding")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                    activeTab === "branding" ? "bg-background text-foreground shadow-xs border" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Palette className="h-3.5 w-3.5 text-sky-500" /> Brand & Logo
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("footer")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                    activeTab === "footer" ? "bg-background text-foreground shadow-xs border" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Settings2 className="h-3.5 w-3.5 text-sky-500" /> Footer
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("code")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors ${
                    activeTab === "code" ? "bg-background text-foreground shadow-xs border" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Code2 className="h-3.5 w-3.5 text-amber-500" /> Raw HTML
                </button>
              </div>

              {/* Controls Scrollable Form Area */}
              <div className="flex-1 p-6 overflow-y-auto space-y-5">
                {/* 1. CTA BUTTON & URL CONFIGURATION TAB */}
                {activeTab === "cta" && (
                  <div className="space-y-4">
                    <div className="p-4 rounded-xl border border-sky-500/30 bg-sky-500/5 space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
                          <LinkIcon className="h-4 w-4 text-sky-500" /> CTA Destination URL & Shortcode Router
                        </span>
                        <Badge variant="outline" className="text-[10px] text-sky-500 border-sky-500/30">
                          Live Active Route
                        </Badge>
                      </div>

                      {/* Custom URL Input Field */}
                      <div className="space-y-1.5">
                        <div className="flex items-center justify-between">
                          <label className="text-[11px] font-bold text-foreground">
                            Button Action URL (Custom URL or Shortcode)
                          </label>
                          <span className="text-[10px] text-muted-foreground">
                            Admin can type any URL or select a preset below
                          </span>
                        </div>
                        <Input
                          value={currentConfig.ctaLink}
                          onChange={(e) => updateField("ctaLink", e.target.value)}
                          placeholder="e.g. {{ .ConfirmationURL }} or https://geflowai.com/reset-password"
                          className="h-10 text-xs font-mono bg-background border-border"
                        />
                      </div>

                      {/* Preset Action URLs for Current Intent */}
                      <div className="space-y-2 pt-1">
                        <label className="text-[11px] font-bold text-foreground block">
                          Recommended URL Presets for {currentTpl.name}:
                        </label>
                        <div className="grid grid-cols-1 gap-2">
                          {currentPresets.map((preset) => {
                            const isCurrent = currentConfig.ctaLink === preset.url;
                            return (
                              <div
                                key={preset.url}
                                onClick={() => updateField("ctaLink", preset.url)}
                                className={`p-2.5 rounded-xl border text-left cursor-pointer transition-all ${
                                  isCurrent
                                    ? "border-sky-500 bg-sky-500/10 text-sky-500 shadow-xs"
                                    : "border-border/70 bg-background/50 hover:bg-background text-muted-foreground hover:text-foreground"
                                }`}
                              >
                                <div className="flex items-center justify-between gap-1">
                                  <span className="text-xs font-bold">{preset.label}</span>
                                  {preset.badge && (
                                    <Badge variant="secondary" className="text-[9px] py-0 bg-emerald-500/10 text-emerald-500">
                                      {preset.badge}
                                    </Badge>
                                  )}
                                </div>
                                <code className="text-[11px] font-mono block mt-0.5 text-foreground/80 break-all">
                                  {preset.url}
                                </code>
                                <p className="text-[10px] text-muted-foreground mt-0.5 leading-normal">
                                  {preset.description}
                                </p>
                              </div>
                            );
                          })}
                        </div>
                      </div>

                      {/* Interactive Shortcode Tag Insert Chips */}
                      <div className="space-y-1.5 pt-1">
                        <label className="text-[11px] font-bold text-muted-foreground block">
                          Insert Dynamic Supabase Variables (Click to Add):
                        </label>
                        <div className="flex flex-wrap gap-1.5">
                          {SHORTCODE_TAGS.map((s) => (
                            <button
                              key={s.tag}
                              type="button"
                              title={s.desc}
                              onClick={() => {
                                const current = currentConfig.ctaLink || "";
                                updateField("ctaLink", current ? `${current}${s.tag}` : s.tag);
                              }}
                              className="px-2.5 py-1 rounded-lg border border-border bg-background hover:bg-sky-500/10 hover:border-sky-500/30 text-sky-500 text-[11px] font-mono font-semibold transition-colors flex items-center gap-1"
                            >
                              <span>{s.tag}</span>
                            </button>
                          ))}
                        </div>
                      </div>

                      {/* CTA Button Label Text */}
                      <div className="pt-2 border-t border-border/60">
                        <label className="text-[11px] font-bold text-foreground block mb-1">
                          CTA Button Label / Text
                        </label>
                        <Input
                          value={currentConfig.ctaText}
                          onChange={(e) => updateField("ctaText", e.target.value)}
                          placeholder="e.g. 🔒 Reset Password & Set New Credentials"
                          className="h-9 text-xs font-medium bg-background"
                        />
                      </div>

                      {/* Button Colors & Curvature */}
                      <div className="grid grid-cols-2 gap-3 pt-1">
                        <div>
                          <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                            Button Background Color
                          </label>
                          <div className="flex items-center gap-2">
                            <input
                              type="color"
                              value={currentConfig.ctaBgColor || "#38bdf8"}
                              onChange={(e) => updateField("ctaBgColor", e.target.value)}
                              className="h-8 w-10 rounded border cursor-pointer bg-transparent"
                            />
                            <Input
                              value={currentConfig.ctaBgColor}
                              onChange={(e) => updateField("ctaBgColor", e.target.value)}
                              className="h-8 text-xs font-mono bg-background"
                            />
                          </div>
                        </div>

                        <div>
                          <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                            Button Text Color
                          </label>
                          <div className="flex items-center gap-2">
                            <input
                              type="color"
                              value={currentConfig.ctaTextColor || "#041017"}
                              onChange={(e) => updateField("ctaTextColor", e.target.value)}
                              className="h-8 w-10 rounded border cursor-pointer bg-transparent"
                            />
                            <Input
                              value={currentConfig.ctaTextColor}
                              onChange={(e) => updateField("ctaTextColor", e.target.value)}
                              className="h-8 text-xs font-mono bg-background"
                            />
                          </div>
                        </div>
                      </div>

                      <div className="pt-1">
                        <label className="text-[11px] font-semibold text-muted-foreground block mb-1.5">
                          Button Shape (Border Radius)
                        </label>
                        <div className="grid grid-cols-4 gap-2">
                          {[
                            { label: "Subtle (8px)", val: "8px" },
                            { label: "Rounded (12px)", val: "12px" },
                            { label: "Curved (16px)", val: "16px" },
                            { label: "Pill (9999px)", val: "9999px" },
                          ].map((shape) => (
                            <button
                              key={shape.val}
                              type="button"
                              onClick={() => updateField("ctaBorderRadius", shape.val)}
                              className={`p-2 rounded-lg text-[11px] font-semibold border transition-all ${
                                currentConfig.ctaBorderRadius === shape.val
                                  ? "border-sky-500 bg-sky-500/10 text-sky-500"
                                  : "border-border text-muted-foreground hover:bg-muted"
                              }`}
                            >
                              {shape.label}
                            </button>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* 2. CONTENT & TEXT TAB */}
                {activeTab === "content" && (
                  <div className="space-y-4">
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between">
                        <label className="text-xs font-bold text-foreground flex items-center gap-1.5">
                          <Mail className="h-3.5 w-3.5 text-sky-500" /> Email Subject Line
                        </label>
                        <button
                          type="button"
                          onClick={() => handleCopy(currentConfig.subject, "Subject")}
                          className="text-[11px] text-sky-500 hover:underline font-semibold"
                        >
                          Copy Subject
                        </button>
                      </div>
                      <Input
                        value={currentConfig.subject}
                        onChange={(e) => updateField("subject", e.target.value)}
                        placeholder="Subject line..."
                        className="h-10 text-xs font-medium"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-foreground block">
                        Headline Title (H1)
                      </label>
                      <Input
                        value={currentConfig.title}
                        onChange={(e) => updateField("title", e.target.value)}
                        placeholder="e.g. Your One-Time Login Link"
                        className="h-10 text-xs font-bold"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-foreground block">
                        Body Description Instructions
                      </label>
                      <Textarea
                        value={currentConfig.description}
                        onChange={(e) => updateField("description", e.target.value)}
                        rows={4}
                        placeholder="Instruction text..."
                        className="text-xs leading-relaxed"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-foreground block">
                        Security Disclaimer & Expiration Notice
                      </label>
                      <Input
                        value={currentConfig.securityNote}
                        onChange={(e) => updateField("securityNote", e.target.value)}
                        placeholder="e.g. This link expires in 10 minutes..."
                        className="h-9 text-xs text-muted-foreground"
                      />
                    </div>
                  </div>
                )}

                {/* 3. BRANDING & LOGO TAB */}
                {activeTab === "branding" && (
                  <div className="space-y-4">
                    {/* Logo Config */}
                    <div className="p-4 rounded-xl border border-border bg-muted/20 space-y-3">
                      <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
                        <ImageIcon className="h-4 w-4 text-sky-500" /> Header Logo & Branding
                      </span>

                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <div>
                            <p className="text-xs font-semibold text-foreground">Custom Logo Image</p>
                            <p className="text-[11px] text-muted-foreground">
                              {settings?.logo_url ? "Default project logo is active" : "Using brand text fallback"}
                            </p>
                          </div>
                          <button
                            type="button"
                            onClick={() => updateField("useCustomLogo", !currentConfig.useCustomLogo)}
                            className={`px-2.5 py-1 rounded-md text-xs font-semibold border transition-colors ${
                              currentConfig.useCustomLogo
                                ? "bg-sky-500 text-white border-sky-600"
                                : "bg-muted border-border text-muted-foreground"
                            }`}
                          >
                            {currentConfig.useCustomLogo ? "Custom URL Active" : "Default Project Logo"}
                          </button>
                        </div>

                        {currentConfig.useCustomLogo && (
                          <div className="space-y-1.5 pt-1">
                            <label className="text-[11px] font-semibold text-muted-foreground block">
                              Custom Logo Image URL
                            </label>
                            <Input
                              value={currentConfig.logoUrl || ""}
                              onChange={(e) => updateField("logoUrl", e.target.value)}
                              placeholder="https://geflowai.com/logo.png"
                              className="h-9 text-xs font-mono"
                            />
                          </div>
                        )}

                        <div className="grid grid-cols-2 gap-3 pt-1">
                          <div>
                            <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                              Brand Name Text
                            </label>
                            <Input
                              value={currentConfig.brandName}
                              onChange={(e) => updateField("brandName", e.target.value)}
                              placeholder="GeFlow"
                              className="h-8 text-xs font-bold"
                            />
                          </div>
                          <div>
                            <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                              Brand Accent Color
                            </label>
                            <div className="flex items-center gap-2">
                              <input
                                type="color"
                                value={currentConfig.brandAccent || "#38bdf8"}
                                onChange={(e) => updateField("brandAccent", e.target.value)}
                                className="h-8 w-10 rounded border cursor-pointer bg-transparent"
                              />
                              <Input
                                value={currentConfig.brandAccent}
                                onChange={(e) => updateField("brandAccent", e.target.value)}
                                className="h-8 text-xs font-mono"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Badge Pill Config */}
                    <div className="p-4 rounded-xl border border-border bg-muted/20 space-y-3">
                      <span className="text-xs font-bold text-foreground block">
                        Header Tag / Badge
                      </span>
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                            Badge Text
                          </label>
                          <Input
                            value={currentConfig.badgeText}
                            onChange={(e) => updateField("badgeText", e.target.value)}
                            placeholder="e.g. Security Notice"
                            className="h-8 text-xs font-medium"
                          />
                        </div>
                        <div>
                          <label className="text-[11px] font-semibold text-muted-foreground block mb-1">
                            Badge Accent Color
                          </label>
                          <div className="flex items-center gap-2">
                            <input
                              type="color"
                              value={currentConfig.badgeColor || "#38bdf8"}
                              onChange={(e) => updateField("badgeColor", e.target.value)}
                              className="h-8 w-10 rounded border cursor-pointer bg-transparent"
                            />
                            <Input
                              value={currentConfig.badgeColor}
                              onChange={(e) => updateField("badgeColor", e.target.value)}
                              className="h-8 text-xs font-mono"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* 4. FOOTER TAB */}
                {activeTab === "footer" && (
                  <div className="space-y-4">
                    <div className="space-y-3">
                      <div>
                        <label className="text-xs font-bold text-foreground block mb-1">
                          Support Email Address
                        </label>
                        <Input
                          value={currentConfig.footerSupportEmail}
                          onChange={(e) => updateField("footerSupportEmail", e.target.value)}
                          placeholder="support@geflowai.com"
                          className="h-9 text-xs"
                        />
                      </div>

                      <div>
                        <label className="text-xs font-bold text-foreground block mb-1">
                          Site Link Dynamic Tag / URL
                        </label>
                        <Input
                          value={currentConfig.footerSiteUrl}
                          onChange={(e) => updateField("footerSiteUrl", e.target.value)}
                          placeholder="{{ .SiteURL }}"
                          className="h-9 text-xs font-mono"
                        />
                      </div>

                      <div>
                        <label className="text-xs font-bold text-foreground block mb-1">
                          Footer Platform Label
                        </label>
                        <Input
                          value={currentConfig.footerText}
                          onChange={(e) => updateField("footerText", e.target.value)}
                          placeholder="GeFlow Business Management Platform"
                          className="h-9 text-xs"
                        />
                      </div>
                    </div>
                  </div>
                )}

                {/* 5. RAW HTML TAB */}
                {activeTab === "code" && (
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-bold text-foreground">Custom Raw HTML Code</label>
                      <button
                        type="button"
                        onClick={() => {
                          const toggleRaw = !currentConfig.useRawHtml;
                          updateField("useRawHtml", toggleRaw);
                          if (toggleRaw && !currentConfig.rawHtml) {
                            updateField("rawHtml", buildHtmlFromFields(selectedId, currentConfig, settings?.logo_url));
                          }
                        }}
                        className={`text-[11px] font-semibold px-2 py-1 rounded-md border ${
                          currentConfig.useRawHtml
                            ? "bg-amber-500/10 border-amber-500/30 text-amber-500"
                            : "bg-muted border-border text-muted-foreground"
                        }`}
                      >
                        {currentConfig.useRawHtml ? "Raw HTML Mode Active" : "Enable Raw HTML Mode"}
                      </button>
                    </div>
                    <Textarea
                      value={currentConfig.rawHtml || finalHtml}
                      onChange={(e) => {
                        updateField("useRawHtml", true);
                        updateField("rawHtml", e.target.value);
                      }}
                      rows={18}
                      className="font-mono text-xs p-3.5 bg-background resize-none border-border"
                      placeholder="Paste custom HTML..."
                    />
                  </div>
                )}
              </div>
            </div>

            {/* Right Column: Instant Live Preview */}
            <div className="lg:col-span-6 flex flex-col h-full overflow-hidden bg-muted/20 dark:bg-black/30 p-5">
              <div className="flex items-center justify-between pb-3 border-b border-border/70 flex-shrink-0">
                <div className="flex items-center gap-2">
                  <Eye className="h-4 w-4 text-sky-500" />
                  <span className="font-bold text-xs text-foreground">Real-Time Instant Preview</span>
                </div>
                <Badge variant="outline" className="text-[10px] text-muted-foreground">
                  Updated Live
                </Badge>
              </div>

              <div className="flex-1 mt-4 flex items-start justify-center overflow-y-auto">
                <div className="w-full max-w-[540px] shadow-xl rounded-2xl border border-border bg-[#0c0f17] overflow-hidden">
                  <div className="bg-[#131825] px-4 py-2 border-b border-[#1e293b] flex items-center justify-between text-[11px] text-slate-400">
                    <div className="truncate font-semibold max-w-[75%]">
                      <span className="text-slate-500">Subject:</span>{" "}
                      {currentConfig.subject.replace("{{ .Token }}", "849201")}
                    </div>
                    <span className="text-emerald-400 font-mono text-[9px] bg-emerald-500/10 px-1.5 py-0.5 rounded-full">
                      Valid HTML
                    </span>
                  </div>

                  <iframe
                    title="Live Preview"
                    srcDoc={renderedPreviewHtml}
                    className="w-full h-[500px] border-none bg-[#0c0f17]"
                  />
                </div>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default EmailTemplatesManager;
