import LegalPage from "@/components/LegalPage";

const Disclaimer = () => (
  <LegalPage
    title="Disclaimer"
    lastUpdated="April 17, 2026"
    sections={[
      {
        id: "general",
        title: "General Disclaimer",
        body: (
          <>
            <p>The information, tools, dashboards, calculators, financial summaries, inventory recommendations, supplier suggestions, automated insights, and any other content (collectively, "Content") provided through the GeFlow business operating system (the "Service") are intended for general informational and operational purposes only. While we have invested significant engineering effort to ensure that Content is accurate, current, reliable, and useful, we make no warranties or representations about the accuracy, completeness, or suitability of Content for any particular purpose.</p>
            <p>Use of the Service and reliance on any Content is strictly at your own risk. GeFlow, Gepard Tech, our affiliates, partners, contributors, sub-processors, and licensors expressly disclaim all liability for any losses, damages, or adverse outcomes — financial, operational, reputational, or otherwise — arising from your use of, or inability to use, the Service or any Content presented through it.</p>
            <p>This Disclaimer is incorporated into and forms part of our Terms of Service. By accessing or using the Service in any manner, you acknowledge that you have read, understood, and agreed to be bound by this Disclaimer in its entirety.</p>
          </>
        ),
      },
      {
        id: "no-professional-advice",
        title: "No Professional Advice",
        body: (
          <>
            <p>GeFlow is a general-purpose business operating system. It is not, and is not intended to be, a substitute for professional advice from qualified accountants, tax advisors, lawyers, regulatory consultants, medical professionals, or other licensed experts.</p>
            <p>Any financial summaries, profit calculations, tax estimates, depreciation schedules, balance-sheet snapshots, or similar reports produced by the Service are computational outputs based on the data you have entered. They do not constitute accounting, audit, tax, legal, investment, or financial advice. You must consult a qualified professional before making decisions based on any output of the Service, and you assume full responsibility for the consequences of any business decision you make.</p>
            <p>Pharmacy-specific features — including expiry-date warnings, batch-tracking visualizations, and stock-level alerts for pharmaceutical inventory — are operational tools to assist competent pharmacists in their work. They are not medical or pharmaceutical advice and must never be relied upon to make clinical decisions about patient care, drug substitution, dosage, or interactions. All pharmaceutical operations using GeFlow must remain under the supervision of a qualified, licensed pharmacist who bears full professional responsibility.</p>
          </>
        ),
      },
      {
        id: "accuracy",
        title: "Accuracy and Completeness of Information",
        body: (
          <>
            <p>The Service relies fundamentally on the data you and your team enter, import, scan, or otherwise submit. We have implemented validation rules, type checks, range checks, and anomaly-detection heuristics to help reduce input errors, but no automated system can fully prevent data-entry mistakes, omissions, duplications, or inconsistencies.</p>
            <p>You are solely responsible for verifying the accuracy and completeness of all data submitted to and stored within your workspace. Reports, analytics, forecasts, and recommendations produced by the Service are only as reliable as the underlying data; the principle of "garbage in, garbage out" applies. We strongly recommend periodic data audits, cycle counts of physical inventory, reconciliation of financial summaries against bank statements, and cross-checks against authoritative external sources.</p>
            <p>Where the Service displays third-party data — including currency exchange rates, supplier catalog information, public business directories, or shipping carrier rate tables — we make no warranty as to the accuracy, currency, or completeness of that data. Third-party data is provided "as is" and may change without notice.</p>
            <p>Forecasts, predictions, and recommendations generated by machine-learning components of the Service are statistical estimates based on historical patterns. Past performance does not guarantee future results. Markets, supply chains, and consumer behavior can change abruptly in ways that no forecasting model can anticipate.</p>
          </>
        ),
      },
      {
        id: "external",
        title: "External Links and Third-Party Integrations",
        body: (
          <>
            <p>The Service may contain links to third-party websites, applications, marketplaces, payment processors, accounting platforms, shipping carriers, and other external resources that are not owned, operated, or controlled by GeFlow. We provide these links and integrations solely as a convenience and do not endorse, sponsor, or assume any responsibility for the content, policies, practices, security, or reliability of any third party.</p>
            <p>When you enable a third-party integration — whether to synchronize accounting data, accept payments, dispatch shipments, send marketing emails, or otherwise — you do so at your own risk and subject to the terms of service and privacy policy of that third party. We are not responsible for any loss, damage, data breach, billing error, or other adverse outcome arising from your use of, or interaction with, any third-party platform, even when accessed through GeFlow.</p>
            <p>Information transmitted to or received from third-party integrations is governed by the privacy and security practices of those third parties. We strongly recommend reviewing each integration's terms and privacy policy before enabling it.</p>
          </>
        ),
      },
      {
        id: "availability",
        title: "Service Availability and Performance",
        body: (
          <>
            <p>While we strive to maintain high availability — with a 99.9% uptime Service Level Agreement for Premium and Lifetime Premium customers — we do not guarantee that the Service will be uninterrupted, error-free, or available at all times. The Service may be temporarily unavailable due to scheduled maintenance, unscheduled emergencies, infrastructure failures, denial-of-service attacks, force majeure events, or factors outside our reasonable control.</p>
            <p>You acknowledge that internet connectivity, browser compatibility, device performance, and local network configuration are outside our control and may affect your experience of the Service. Issues stemming from these external factors are not the responsibility of GeFlow.</p>
            <p>You are responsible for maintaining adequate offline backups of critical business data. While we perform automated daily backups of all workspace data, we recommend that you periodically export and store local copies of important records for additional resilience.</p>
            <p>Compatibility with specific browsers, operating systems, point-of-sale hardware, barcode scanners, receipt printers, or cash drawers may change over time as we update the Service. We will provide reasonable notice of any planned compatibility changes, but you are responsible for ensuring that your hardware and software environment meets the current published requirements at geflow.io/system-requirements.</p>
          </>
        ),
      },
      {
        id: "endorsements",
        title: "Testimonials, Endorsements, and Case Studies",
        body: (
          <>
            <p>Testimonials, customer quotes, case studies, ratings, and endorsements published on our website or within the Service reflect the personal experiences and opinions of individual customers at the time those statements were given. They are not guarantees that you or your business will achieve similar results.</p>
            <p>Business outcomes depend on many variables — industry, market conditions, team capability, capital, location, regulatory environment, and execution discipline — that GeFlow neither controls nor influences. We make no representation that any specific operational improvement, cost reduction, revenue increase, or other outcome will result from your use of the Service.</p>
            <p>Where customer testimonials reference specific results (for example, "we reduced stockouts by 40% in three months"), those results were achieved by that customer in their specific operating context and should not be interpreted as a typical or expected outcome for other businesses.</p>
          </>
        ),
      },
      {
        id: "ip",
        title: "Intellectual Property and Brand References",
        body: (
          <>
            <p>References to third-party products, brands, companies, trademarks, or service marks within the Service or our marketing materials are made for descriptive, comparative, or compatibility purposes only. Such references do not constitute endorsement, sponsorship, partnership, or affiliation by or with those third parties, unless explicitly stated in writing.</p>
            <p>All trademarks, service marks, trade names, and logos referenced are the property of their respective owners. The GeFlow name, logo, and associated marks are trademarks of Gepard Tech.</p>
          </>
        ),
      },
      {
        id: "limitation",
        title: "Limitation of Liability",
        body: (
          <>
            <p>To the maximum extent permitted by applicable law, GeFlow, Gepard Tech, our directors, officers, employees, contractors, agents, suppliers, sub-processors, and licensors disclaim all liability — whether arising in contract, tort (including negligence), strict liability, or any other theory — for any direct, indirect, incidental, special, consequential, exemplary, or punitive damages, including but not limited to loss of profits, revenue, business opportunities, goodwill, data, or use, arising out of or related to your use of the Service or any Content.</p>
            <p>Without limiting the foregoing, in no event will our total cumulative liability for all claims arising out of or related to your use of the Service exceed the greater of (a) the amounts you paid to us in the 12 months immediately preceding the event giving rise to the claim, or (b) one hundred United States dollars (USD $100).</p>
            <p>Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the limitations above may not apply to you. In such jurisdictions, our liability is limited to the maximum extent permitted by law.</p>
          </>
        ),
      },
      {
        id: "indemnification",
        title: "Indemnification",
        body: (
          <>
            <p>You agree to indemnify, defend, and hold harmless GeFlow, Gepard Tech, our affiliates, and our respective directors, officers, employees, contractors, and agents from and against any and all claims, demands, lawsuits, damages, liabilities, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your use of the Service; (b) your violation of these Terms, our Privacy Policy, or any other agreement with us; (c) your violation of any third-party right, including any intellectual-property, privacy, or contractual right; (d) your Customer Data, including any claim that your Customer Data caused damage to a third party; or (e) any business decision you made based on Content provided by the Service.</p>
            <p>We reserve the right, at our own expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you, and you agree to cooperate fully with our defense of such claims. You may not settle any claim without our prior written consent.</p>
          </>
        ),
      },
      {
        id: "changes",
        title: "Changes to This Disclaimer",
        body: (
          <>
            <p>We reserve the right to modify this Disclaimer at any time, with or without prior notice. Material changes will be communicated by email and through in-product notification at least 14 days before they take effect, and the "Last Updated" date at the top of this page will be revised accordingly.</p>
            <p>Your continued use of the Service following the effective date of any updated Disclaimer constitutes your acceptance of the revised terms. If you do not agree with the revised Disclaimer, you must discontinue use of the Service. Historical versions of this Disclaimer are archived and available upon request at legal@geflow.io.</p>
            <p>Questions about this Disclaimer should be directed to legal@geflow.io. We typically respond to legal inquiries within two business days. For urgent matters concerning ongoing operations, please also notify support@geflow.io for parallel handling.</p>
          </>
        ),
      },
    ]}
  />
);

export default Disclaimer;
